'use client';
import {routeToken} from '@/lib/football/consumer.mjs';
import {useEffect,useState} from 'react';
type Data=Record<string,any>;
export default function FootballEntity({id}:{id:string}){const [data,setData]=useState<Data|null>(null),[error,setError]=useState('');useEffect(()=>{const c=new AbortController();void fetch(`/api/intelligence?view=entity&id=${encodeURIComponent(id)}`,{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Profile temporarily unavailable. Please retry.');return r.json();}).then(d=>setData(d as Data)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[id]);const e=data?.entity;return <div className="intel"><main className="match-center"><nav className="match-nav"><a href="/football">← Football intelligence</a><a href="/football/search">Search</a><a href="/football/predictions">Model performance</a></nav>{error&&<p role="alert">{error}</p>}<header className="match-hero"><span>ENTITY PROFILE · {data?.kind??'Football'}</span><h1 style={{fontSize:'clamp(32px,5vw,56px)',margin:'20px 0'}}>{e?.name??(data?'Profile not found':'Loading profile…')}</h1><p>{e?.position??e?.stadium??'Sourced identity and recorded performance'}</p><p>{typeof e?.country==='object'?e.country?.name:e?.country??'Country not verified'}{data?.updatedAt?` · Updated ${new Date(data.updatedAt).toLocaleString()}`:''}</p>{e?.identitySourceUrl&&<a href={e.identitySourceUrl} target="_blank" rel="noreferrer">Verified identity source ↗</a>}</header>
 {data?.form&&<section className="intel-panel"><h2>Form and strength</h2><div className="intel-stats">{['overall','home','away'].map(k=><div key={k}><span>{k} · {data.form[k].games} matches</span><strong style={{fontSize:18}}>{data.form[k].results.join(' · ')||'No recorded results'}</strong></div>)}</div><p>Imported-coverage Elo: {data.rating?Math.round(data.rating):'Insufficient history'}. Results outside imported coverage are not assumed.</p></section>}
 {data?.kind==='player'&&<section className="intel-panel"><h2>Recorded participation</h2><p>{data.appearances?.length?`${data.totals.appearances} appearances · ${Number(data.totals.minutes).toFixed(1)} recorded/derived minutes`:'No appearance/minute records have been retrieved. Starting probability cannot be estimated from membership alone.'}</p>{data.team&&<a href={`/football/team/${routeToken(data.team.id)}`}>{data.team.name}</a>}<div>{data.memberships?.map((m:Data)=><p key={m.teamId}><a href={`/football/team/${routeToken(m.teamId)}`}>{m.teamName}</a> ? {m.start?`Membership recorded from ${new Date(m.start).getFullYear()}`:'Start date unknown'} ? current squad unverified</p>)}</div><p>{e?.membershipNote??'Availability is unknown unless supported by a dated source claim.'}</p></section>}
 {!!data?.competitions?.length&&<section><h2>Competitions</h2><div className="intel-matches">{data.competitions.map((c:Data)=><a className="intel-match" key={c.id} href={c.url}>{c.name}</a>)}</div></section>}
 {data?.kind==='team'&&<section><h2>Player records</h2><p>Membership records are distinct from a confirmed current matchday squad.</p>{!data.players?.length&&<p>No permitted source has supplied player membership records for this club yet.</p>}<div className="intel-matches">{data.players?.map((p:Data)=><a className="intel-match" key={p.id} href={`/football/player/${routeToken(p.id)}`}><h3>{p.name}</h3><p>{p.position??'Position unavailable'}</p><small>{p.membershipNote??p.provider}</small></a>)}</div></section>}
 <section><h2>Upcoming and recent fixtures</h2><div className="intel-matches">{data?.fixtures?.map((f:Data)=><a className="intel-match" key={f.id} href={`/football/match/${encodeURIComponent(f.id)}`}><h3>{f.home.name} — {f.away.name}</h3><p>{f.label} · {new Date(f.startsAt).toLocaleDateString()} · {f.homeScore??'—'} : {f.awayScore??'—'}</p>{f.hasConflict&&<p>Conflicting source claims</p>}</a>)}</div></section>
 {!!data?.news?.length&&<section><h2>Related reporting</h2><div className="intel-news">{data.news.map((n:Data)=><a key={n.id} href={`/football/news/${routeToken(n.id)}`}><p>{n.publisher}</p><h3>{n.headline}</h3><p>{n.association}</p></a>)}</div></section>}
 {!!data?.social?.length&&<section className="intel-panel"><h2>Official account registry</h2>{data.social.map((s:Data)=><p key={s.id}><a href={s.url} target="_blank" rel="noreferrer">{s.platform} · {s.verified?'Verified':'Account association awaiting verification'} ↗</a></p>)}</section>}
 {e?.sourceUrl&&<p><a href={e.sourceUrl} target="_blank" rel="noreferrer">Original data source ↗</a></p>}
 </main></div>;}
