'use client';
import {useEffect,useState,useId} from 'react';
type Data=Record<string,any>;
export default function GlobalSearch(){
 const [q,setQ]=useState(''),[filters,setFilters]=useState<Record<string,string>>({}),[data,setData]=useState<Data>({}),[catalog,setCatalog]=useState<Data>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[recent,setRecent]=useState<string[]>([]),[active,setActive]=useState(-1);const listId=useId();
 useEffect(()=>{const p=new URLSearchParams(location.search);setQ(p.get('q')??'');setFilters(Object.fromEntries(['kind','sport','country','competition','season','team','status','from','to'].filter(k=>p.has(k)).map(k=>[k,p.get(k)!])));try{setRecent(JSON.parse(localStorage.getItem('pitchpredict-searches')??'[]').filter((v:unknown)=>typeof v==='string').slice(0,6));}catch{}void fetch('/api/intelligence?view=catalog').then(r=>r.json()).then(d=>setCatalog(d as Data)).catch(()=>{});},[]);
 const params=()=>{const p=new URLSearchParams({view:'global-search',q});for(const [k,v] of Object.entries(filters))if(v)p.set(k,v);return p;};
 useEffect(()=>{const c=new AbortController(),timer=setTimeout(()=>{if(q.trim().length<2&&!Object.values(filters).some(Boolean)){setData({});setBusy(false);return;}setError('');setBusy(true);setActive(-1);void fetch('/api/intelligence?'+params(),{signal:c.signal}).then(r=>{if(!r.ok)throw Error('Search unavailable. Check your connection and retry.');return r.json();}).then(d=>setData(d as Data)).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});},250);return()=>{c.abort();clearTimeout(timer);};},[q,filters]);
 function remember(){if(q.trim().length<2)return;const next=[q.trim(),...recent.filter(v=>v!==q.trim())].slice(0,6);setRecent(next);try{localStorage.setItem('pitchpredict-searches',JSON.stringify(next));}catch{}}
 async function more(){setBusy(true);try{const p=params();p.set('offset',String(data.nextOffset));const r=await fetch('/api/intelligence?'+p);if(!r.ok)throw Error('More results could not load. Please retry.');const next=await r.json() as Data;setData(current=>({...next,results:[...(current.results??[]),...next.results]}));}catch(e){setError(String(e));}finally{setBusy(false);}}
 const set=(key:string,value:string)=>setFilters(f=>({...f,[key]:value})),countries=[...new Set((catalog.competitions??[]).map((c:Data)=>c.country?.name).filter(Boolean))] as string[];
 return <section className="intel-panel"><h2>Search football intelligence</h2><div className="intel-filters"><label><input aria-label="Global football search" role="combobox" aria-expanded={!!data.results?.length} aria-controls={listId} aria-activedescendant={active>=0?`${listId}-${active}`:undefined} autoComplete="off" placeholder="FC Augsburg, Eintracht Frankfurt, Bundesliga…" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setActive(i=>Math.min(i+1,(data.results?.length??0)-1));}if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(-1,i-1));}if(e.key==='Escape')setActive(-1);if(e.key==='Enter'&&active>=0){remember();location.href=data.results[active].url;}}}/></label><select aria-label="Search result type" value={filters.kind??''} onChange={e=>set('kind',e.target.value)}><option value="">All record types</option>{['team','player','competition','country','fixture','prediction','news'].map(k=><option key={k}>{k}</option>)}</select><select aria-label="Search sport" value={filters.sport??'football'} onChange={e=>set('sport',e.target.value)}><option value="football">Football</option><option value="basketball">Basketball</option></select></div>
 <details><summary>Search filters</summary><div className="intel-filters"><select aria-label="Search country" value={filters.country??''} onChange={e=>set('country',e.target.value)}><option value="">All countries</option>{countries.sort().map(c=><option key={c}>{c}</option>)}</select><select aria-label="Search competition" value={filters.competition??''} onChange={e=>set('competition',e.target.value)}><option value="">All competitions</option>{catalog.competitions?.map((c:Data)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Search season" value={filters.season??''} onChange={e=>set('season',e.target.value)}><option value="">All seasons</option>{catalog.competitions?.filter((c:Data)=>c.id===filters.competition).flatMap((c:Data)=>c.seasons??[]).map((s:Data)=><option key={s.id} value={s.id}>{s.year}</option>)}</select><select aria-label="Search fixture status" value={filters.status??''} onChange={e=>set('status',e.target.value)}><option value="">All statuses</option><option value="NS">Scheduled</option><option value="FT">Finished</option><option value="PST">Postponed</option></select><label>From <input type="date" value={filters.from??''} onChange={e=>set('from',e.target.value)}/></label><label>To <input type="date" value={filters.to??''} onChange={e=>set('to',e.target.value)}/></label><button onClick={()=>setFilters({})}>Clear filters</button></div></details>
 {!q&&recent.length>0&&<p>Recent: {recent.map(v=><button key={v} onClick={()=>setQ(v)} style={{margin:6}}>{v}</button>)}</p>}<p role="status">{error||(busy?'Searching stored football records…':data.reason??(data.total===0?'No matching imported records. Try a shorter name or clear filters.':data.total?`${data.total} matching records`:'Search teams, players, competitions, countries, matches, predictions and news.'))}</p><div className="intel-matches" role="listbox" id={listId} aria-label="Football search results">{data.results?.map((r:Data,i:number)=><a className="intel-match" role="option" aria-selected={active===i} id={`${listId}-${i}`} style={active===i?{outline:'3px solid #1975e8'}:undefined} key={`${r.kind}:${r.id}`} href={r.url} onClick={remember}><strong>{r.name}</strong><p>{r.kind}{r.date?` · ${new Date(r.date).toLocaleDateString()}`:''}</p></a>)}</div>{data.nextOffset!=null&&<button onClick={more} disabled={busy}>Load more search results</button>}</section>;
}
