'use client';
import {useEffect,useState} from 'react';
import NewsCard from './news-card';
import TeamBadge from './team-badge';
import CompetitionPicker from './competition-picker';
import FeaturedMatches from './featured-matches';
import GlobalSearch from './global-search';
import LocalTime,{TimePreference,useTimeZone} from './local-time';
import {useMatchday,MatchdaySelector} from './use-matchday';
import {routeToken} from '@/lib/football/consumer.mjs';
import {ArrowUpRight,Activity,Search,Globe2,ChevronRight,Layers3,Newspaper,Trophy,Users} from 'lucide-react';
type RecordData=Record<string,any>;
const tabs=['Predictions','Fixtures','Leagues','Teams & Players','News'];
function Match({f}:{f:RecordData}){return <a className="intel-match" href={`/football/match/${encodeURIComponent(f.id)}`}><div className="intel-match-meta"><span>{f.competition.name}</span><span>{f.label}</span></div><div className="intel-team"><span className="team-name"><TeamBadge id={f.home.id} name={f.home.name} logo={f.home.logo}/>{f.home.name}</span><b>{f.homeScore??'—'}</b></div><div className="intel-team"><span className="team-name"><TeamBadge id={f.away.id} name={f.away.name} logo={f.away.logo}/>{f.away.name}</span><b>{f.awayScore??'—'}</b></div><div className="intel-match-foot"><LocalTime fixture={{startsAt:f.startsAt,kickoffPrecision:f.kickoffPrecision}}/><ArrowUpRight size={15}/></div></a>}
function Insight({f,initial}:{f:RecordData;initial?:RecordData}){const [analysis,setAnalysis]=useState<RecordData|null>(initial??null);useEffect(()=>{if(initial)return;const c=new AbortController();void fetch('/api/intelligence?view=analysis&id='+encodeURIComponent(f.id),{signal:c.signal}).then(r=>r.json() as Promise<RecordData>).then(d=>setAnalysis(d.analysis)).catch(()=>{});return()=>c.abort();},[f.id,initial]);return <article className="intel-panel insight-card"><Match f={f}/>{analysis?.probabilities?<><p className="intel-eyebrow">MATCH RESULT · MODEL ESTIMATE</p><div className="insight-probabilities">{['Home','Draw','Away'].map((label,i)=><div key={label}><span>{label}</span><strong>{(analysis.probabilities[i]*100).toFixed(1)}%</strong></div>)}</div><p>{analysis.explanations?.slice(0,2).join(' ')}</p><small>Regulation time. Estimates carry uncertainty; they are not guarantees.</small></>:<p>{analysis?.reason??'Explore available form, head-to-head history and match details.'}</p>}</article>}
export default function IntelligenceWorkspace(){
 const {filters,change,ready,query}=useMatchday(),{tab,q,status,competition}=filters;
 const setTab=(tab:string)=>change({tab}),setQ=(q:string)=>change({q}),setStatus=(status:string)=>change({status}),setCompetition=(competition:string)=>change({competition});
 const [data,setData]=useState<RecordData|null>(null),[detail,setDetail]=useState<RecordData|null>(null),[catalog,setCatalog]=useState<RecordData>({}),[error,setError]=useState(''),[matchday,setMatchday]=useState<RecordData|null>(null);const {zone}=useTimeZone();
 useEffect(()=>{if(!ready)return;const controller=new AbortController();async function load(){try{const r=await fetch('/api/intelligence?view=matchday&'+query,{signal:controller.signal});if(!r.ok)throw Error('Matchday unavailable. Check the date range and retry.');const result=await r.json() as RecordData;setMatchday({...result,query});setError('');}catch(e){if(!controller.signal.aborted)setError(String(e));}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},60000);return()=>{controller.abort();clearInterval(timer);};},[query,ready]);
 useEffect(()=>{let active=true;const controller=new AbortController();async function load(){try{const [o,c]=await Promise.all(['overview','catalog'].map(async view=>{const r=await fetch('/api/intelligence?view='+view+'&timezone='+encodeURIComponent(zone??'UTC'),{signal:controller.signal});if(!r.ok)throw Error('Football data is temporarily unavailable. Please retry shortly.');return r.json() as Promise<RecordData>;}));if(active){setData(o);setCatalog(c);setError('');}}catch(e){if(active)setError(String(e));}}void load();const timer=setInterval(()=>{if(!document.hidden)void load();},60000);return()=>{active=false;controller.abort();clearInterval(timer);};},[zone]);
 useEffect(()=>{if(tab!=='News')return;void fetch('/api/intelligence?view=news').then(r=>r.json() as Promise<RecordData>).then(setDetail).catch(()=>setError('News unavailable.'));},[tab]);
 const current=matchday?.query===query?matchday:null,fixtures=current?.fixtures??[],insights=current?.picks??[];
 const featured=current?{today:fixtures,results:fixtures.filter((f:RecordData)=>['FT','FINISHED','1H','2H','HT'].includes(f.status)),upcoming:(insights.length?insights.map((e:RecordData)=>({...e.fixture,recommendation:e.recommendation})):fixtures),note:current.note}:null;
 return <div className="intel"><aside className="intel-sidebar"><a className="intel-brand" href="/football"><span className="intel-symbol">M<span>·</span></span><span>Mnemba Tips<span className="intel-brand-sub">THE GAME, A LITTLE CLEARER</span></span></a><div className="intel-nav-label">EXPLORE FOOTBALL</div><nav aria-label="Main navigation">{tabs.map((t,i)=>{const Icon=[Activity,Layers3,Trophy,Users,Newspaper][i];return <button key={t} className={tab===t?'active':''} onClick={()=>{change({tab:t});}}><Icon size={18}/>{t}</button>})}</nav><div className="intel-sidebar-bottom"><div className="intel-open"><Globe2 size={20}/><strong>The world’s game.<br/>Yours to explore.</strong><p>Matches, meaningful context and stories worth following.</p></div></div></aside>
 <main className="intel-main"><header className="intel-top"><span><span className="intel-dot"/> MNEMBA TIPS</span><TimePreference/><a href="/football/predictions">Prediction history →</a></header>
 {['Predictions','Fixtures'].includes(tab)&&<><MatchdaySelector filters={filters} change={change}/><p role="status">{current?`${current.range.from} → ${current.range.to} · ${current.count} covered matches · ${current.eligible??0} qualifying selections`:'Loading selected matchday…'}</p></>}{tab==='Predictions'?<FeaturedMatches data={featured}/>:<section className="intel-heading"><div className="intel-eyebrow">YOUR FOOTBALL DESK</div><h1>{tab==='News'?'The football briefing.':tab==='Leagues'?'Explore the world’s game.':tab==='Teams & Players'?'The people behind the game.':'Every match. More context.'}</h1><p>Follow the teams, the players and the next ninety minutes.</p></section>}
 {error&&<div className="intel-notice" role="status">{error}</div>}
 {tab==='Predictions'&&<><div className="intel-section-title"><div><span className="intel-eyebrow">LOOKING AHEAD</span><h2>Matchday Picks</h2></div><span className="intel-small">Real fixtures · available analysis</span></div><div className="intel-matches">{insights.map((entry:RecordData)=><Insight key={entry.fixture.id} f={entry.fixture} initial={entry.analysis}/>)}</div>{current&&<p className="intel-panel">{current.note} <a href="/football/shortlists">Published matchday records →</a></p>}<GlobalSearch/></>}
 {tab==='Teams & Players'&&<GlobalSearch/>}
 {['Predictions','Fixtures'].includes(tab)&&<><div className="intel-section-title"><h2>{tab==='Fixtures'?'Fixture explorer':'Selected matchday'}</h2><button onClick={()=>setTab(tab==='Fixtures'?'Predictions':'Fixtures')}>{tab==='Fixtures'?'Match insights':'All fixtures'}<ChevronRight size={16}/></button></div><div className="intel-filters"><label><Search size={17}/><input aria-label="Search fixtures" placeholder="Search teams or competitions" value={q} onChange={e=>setQ(e.target.value)}/></label><CompetitionPicker competitions={catalog.competitions??[]} value={competition} onChange={setCompetition}/><select aria-label="Fixture status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Current & upcoming</option><option value="NS">Scheduled</option><option value="FT">Historical results</option><option value="PST">Postponed</option></select></div><div className="intel-matches">{fixtures.map((f:RecordData)=><Match key={f.id} f={f}/>)}</div>{!fixtures.length&&<p className="intel-panel">{!current?'Loading selected matchday…':current.loading?'Preparing selected matchday…':'No fixtures match this date in available coverage. Explore upcoming fixtures or choose another date.'}</p>}</>}
 {tab==='Leagues'&&<><div className="intel-filters"><label><Search size={17}/><input placeholder="Search leagues" aria-label="Search leagues" value={q} onChange={e=>setQ(e.target.value)}/></label></div><div className="intel-matches">{catalog.competitions?.filter((c:RecordData)=>c.name.toLowerCase().includes(q.toLowerCase())).map((c:RecordData)=><button className="intel-match intel-competition" key={c.id} onClick={()=>{change({competition:(c.providerIds??[c.id]).join(','),tab:'Fixtures',q:''});}}><Trophy size={24}/><h3>{c.name}</h3><p>{c.country?.name??'International'}</p><span>{c.fixtureCount?`${c.fixtureCount.toLocaleString()} recorded fixtures`:'Coverage coming soon'}</span></button>)}</div></>}
 {['Predictions','News'].includes(tab)&&<><div className="intel-section-title"><h2>Beyond the scoreline</h2><button onClick={()=>setTab('News')}>All stories <ArrowUpRight size={16}/></button></div><div className="intel-news">{(tab==='News'?detail?.articles:data?.news)?.slice(0,tab==='News'?100:6).map((n:RecordData)=><NewsCard key={n.id} article={n}/>)}</div></>}
 <footer className="intel-footer"><span className="intel-symbol">M·</span><p>Football, with perspective.<br/><span>Predictions are estimates, never guarantees. Scores are recorded snapshots, not an official live feed.</span><br/><small>Fixture data: OpenFootball and participating providers. Badge metadata: <a href="https://www.thesportsdb.com" target="_blank" rel="noreferrer">TheSportsDB</a>; club marks remain their owners’ property.</small></p></footer>
 </main></div>;
}
