'use client';
import {useEffect,useState} from 'react';
import AdminControls from './admin-controls';
import ModelPerformance from './model-performance';
import FeaturedMatches from './featured-matches';
import GlobalSearch from './global-search';
import {routeToken} from '@/lib/football/consumer.mjs';
import EntityExplorer from './entity-explorer';
import VerificationQueue from './verification-queue';
import {ArrowUpRight,Activity,Search,Globe2,ShieldCheck,RefreshCw,ChevronRight,Layers3,Newspaper,Radio,Trophy} from 'lucide-react';
type RecordData=Record<string,any>;
const tabs=['Overview','Fixtures','Competitions','News','Social','Diagnostics'];
const date=(n:number)=>new Date(n).toLocaleDateString(undefined,{month:'short',day:'numeric'});
function Match({f}:{f:RecordData}){return <a className="intel-match" href={`/football/match/${encodeURIComponent(f.id)}`}><div className="intel-match-meta"><span>{f.competition.name}</span><span>{f.label} · {date(f.startsAt)}</span></div><div className="intel-team"><span>{f.home.name}</span><b>{f.homeScore??'—'}</b></div><div className="intel-team"><span>{f.away.name}</span><b>{f.awayScore??'—'}</b></div><div className="intel-match-foot"><span>{f.provider} · {f.kickoffPrecision==='date'?'Time zone unverified':new Date(f.startsAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><ArrowUpRight size={15}/></div></a>}
export default function IntelligenceWorkspace(){const [tab,setTab]=useState('Overview'),[data,setData]=useState<RecordData|null>(null),[detail,setDetail]=useState<RecordData|null>(null),[q,setQ]=useState(''),[status,setStatus]=useState(''),[country,setCountry]=useState(''),[competition,setCompetition]=useState(''),[catalog,setCatalog]=useState<RecordData>({}),[season,setSeason]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[confederation,setConfederation]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function request(view:string){const r=await fetch(`/api/intelligence?view=${view}`);if(!r.ok)throw new Error('The database is temporarily unavailable. Cached records will return after the update.');return r.json() as Promise<RecordData>;}
 async function refresh(){try{setData(await request('overview'));setCatalog(await request('catalog'));setError('');}catch(e){setError(String(e));}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),60000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{setDetail(null);const view=({Competitions:'catalog',News:'news',Social:'social',Diagnostics:'sources'} as Record<string,string>)[tab];if(view)void request(view).then(setDetail).catch(e=>setError(String(e)));},[tab]);
 useEffect(()=>{if(tab!=='Fixtures')return;const params=new URLSearchParams({view:'fixtures'});for(const [key,value] of Object.entries({competition,country,status,season,from,to}))if(value)params.set(key,value);void fetch('/api/intelligence?'+params).then(r=>r.json()).then(d=>setDetail(d as RecordData)).catch(e=>setError(String(e)));},[tab,competition,country,status,season,from,to]);
 async function more(){const params=new URLSearchParams({view:'fixtures',offset:String(detail?.nextOffset??0)});for(const [key,value] of Object.entries({competition,country,status,season,from,to}))if(value)params.set(key,value);const r=await fetch('/api/intelligence?'+params);const next=await r.json() as RecordData;setDetail(current=>({...next,fixtures:[...(current?.fixtures??[]),...(next.fixtures??[])]}));}
 async function sync(){setBusy(true);try{const r=await fetch('/api/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job:'fixtures'})});const result=await r.json() as RecordData;if(!r.ok||result.errors?.length)throw new Error(result.error??result.errors.join('; '));await refresh();}catch(e){setError(String(e));}finally{setBusy(false);}}
 const fixtures=(tab==='Fixtures'?detail?.fixtures:data?.today)??[],filtered=fixtures.filter((f:RecordData)=>(!q||`${f.home.name} ${f.away.name} ${f.competition.name}`.toLowerCase().includes(q.toLowerCase()))&&(!status||f.status===status)&&(!country||f.competition.country?.id===country)&&(!competition||f.competition.id===competition)&&(!confederation||f.competition.confederation===confederation));
 return <div className="intel"><aside className="intel-sidebar"><a className="intel-brand" href="/football"><span className="intel-symbol">P<span>°</span></span><span>PitchPredict<span className="intel-brand-sub">FOOTBALL INTELLIGENCE</span></span></a><div className="intel-nav-label">YOUR WORKSPACE</div><nav>{tabs.map((t,i)=>{const Icon=[Activity,Layers3,Trophy,Newspaper,Radio,ShieldCheck][i];return <button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setQ('')}}><Icon size={18}/>{t}{t==='Overview'&&<span className="intel-dot"/>}</button>})}</nav><div className="intel-sidebar-bottom"><div className="intel-open"><Globe2 size={20}/><strong>The world’s game.<br/>Open to everyone.</strong><p>Free sources. Original analysis. Evidence you can inspect.</p></div><a href="/lab">Football & basketball studio <ArrowUpRight size={15}/></a><a href="/football/classic">Advanced match workspace <ArrowUpRight size={15}/></a></div></aside>
 <main className="intel-main"><header className="intel-top"><span><span className="intel-dot"/> GLOBAL FOOTBALL DESK</span><div><span className="intel-date">{data?new Date(data.updatedAt).toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}):'Local football desk'}</span><button onClick={sync} disabled={busy} aria-label="Update fixtures"><RefreshCw size={16} className={busy?'intel-spin':''}/>{busy?'Updating':'Update'}</button></div></header>
 {tab==='Overview'&&<FeaturedMatches data={data}/>}<section className="intel-heading" hidden={tab==='Overview'}><div className="intel-eyebrow">THE BIGGER PICTURE</div><h1>{tab==='Overview'?<>Know the game.<br/><em>See what’s next.</em></>:tab==='Diagnostics'?'Behind every insight.':tab==='Social'?'From the source.':tab==='News'?'The football briefing.':tab==='Competitions'?'Explore the world’s game.':'Every match. More context.'}</h1><p>{tab==='Overview'?'Your daily view of global football — fixtures, form and the stories shaping the next ninety minutes.':'Traceable football information, with clear source coverage and honest uncertainty.'}</p><div className="intel-pills"><span><ShieldCheck size={14}/> Free-source intelligence</span><span><Activity size={14}/> Independently calculated</span><span>Updated {data?new Date(data.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'on connection'}</span></div></section>
 {error&&<div className="intel-notice" role="status">{error}</div>}
 {tab==='Overview'&&<><GlobalSearch/><ModelPerformance/></>}<div className="intel-stats">{[['Fixtures',data?.counts?.fixtures],['Teams',data?.counts?.teams],['Competitions',data?.counts?.competitions],['Evidence claims',data?.counts?.claims]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value?.toLocaleString()??'—'}</strong><span className="intel-stat-note">in your local database</span></div>)}</div>
 {['Overview','Fixtures'].includes(tab)&&<><div className="intel-section-title"><div><span className="intel-eyebrow">MATCH CENTRE</span><h2>{tab==='Fixtures'?'Fixture explorer':'On the calendar today ? UTC'}</h2></div><button onClick={()=>setTab(tab==='Fixtures'?'Overview':'Fixtures')}>{tab==='Fixtures'?'Overview':'All fixtures'} <ChevronRight size={16}/></button></div><div className="intel-filters"><label><Search size={17}/><input aria-label="Search fixtures" placeholder="Search teams or competitions" value={q} onChange={e=>setQ(e.target.value)}/></label><select aria-label="Country" value={country} onChange={e=>setCountry(e.target.value)}><option value="">All countries</option>{catalog.countries?.map((c:RecordData)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Competition" value={competition} onChange={e=>setCompetition(e.target.value)}><option value="">All competitions</option>{catalog.competitions?.map((c:RecordData)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="Fixture status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="NS">Scheduled</option><option value="FT">Final</option><option value="PST">Postponed</option></select>{tab==='Fixtures'&&<><select aria-label="Confederation" value={confederation} onChange={e=>setConfederation(e.target.value)}><option value="">All confederations</option>{['UEFA','CAF','AFC','CONMEBOL','CONCACAF','OFC'].map(c=><option key={c}>{c}</option>)}</select><select aria-label="Season" value={season} onChange={e=>setSeason(e.target.value)}><option value="">All seasons</option>{catalog.seasons?.filter((s:RecordData)=>!competition||s.competitionId===competition).map((s:RecordData)=><option key={s.id} value={s.id}>{s.year} ? {catalog.competitions?.find((c:RecordData)=>c.id===s.competitionId)?.name}</option>)}</select><input style={{width:140}} type="date" aria-label="From date" value={from} onChange={e=>setFrom(e.target.value)}/><input style={{width:140}} type="date" aria-label="To date" value={to} onChange={e=>setTo(e.target.value)}/></>}</div><div className="intel-matches">{filtered.map((f:RecordData)=><Match key={f.id} f={f}/>)}</div>{tab==='Fixtures'&&detail?.nextOffset!=null&&<button onClick={()=>void more()}>Load next 500 records</button>}{!filtered.length&&<div className="intel-empty"><Globe2/><h3>{data?'No matching fixtures in the current coverage.':'Opening your football desk…'}</h3><p>Coverage depends on publication by free sources. Explore upcoming matches and the recorded results below.</p></div>}
 {tab==='Overview'&&<><div className="intel-section-title"><div><span className="intel-eyebrow">LOOKING AHEAD</span><h2>Next on the pitch</h2></div><span className="intel-small">Scheduled · subject to change</span></div><div className="intel-matches">{data?.upcoming?.slice(0,8).map((f:RecordData)=><Match key={f.id} f={f}/>)}</div><div className="intel-section-title"><div><span className="intel-eyebrow">THE RECORD</span><h2>Latest recorded results</h2></div><span className="intel-small">Historical evidence, never presented as live</span></div><div className="intel-matches">{data?.results?.slice(0,8).map((f:RecordData)=><Match key={f.id} f={f}/>)}</div></>}
 </>}
 {tab==='Competitions'&&<><EntityExplorer/><div className="intel-filters"><label><Search size={17}/><input placeholder="Search competitions" aria-label="Search competitions" value={q} onChange={e=>setQ(e.target.value)}/></label></div><div className="intel-matches">{detail?.competitions?.filter((c:RecordData)=>c.name.toLowerCase().includes(q.toLowerCase())).map((c:RecordData)=><button className="intel-match intel-competition" key={c.id} onClick={()=>{setCompetition(c.id);setTab('Fixtures')}}><Trophy size={24}/><h3>{c.name}</h3><p>{c.country?.name??'Country not verified'} · {c.provider}</p><span>{c.seasons.length?`${c.seasons.length} seasons`:'Catalog entry · fixtures not yet imported'}</span></button>)}</div></>}
 {['Overview','News'].includes(tab)&&<><div className="intel-section-title"><div><span className="intel-eyebrow">BEYOND THE SCORELINE</span><h2>News intelligence</h2></div><button onClick={()=>setTab('News')}>The full briefing <ArrowUpRight size={16}/></button></div><div className="intel-news">{(tab==='News'?detail?.articles:data?.news)?.slice(0,tab==='News'?100:6).map((n:RecordData)=><a key={n.id??n.url} href={`/football/news/${routeToken(n.id)}`}><div className="intel-news-source">{n.publisher??n.source?.name??n.source??n.provider} <ArrowUpRight size={16}/></div><h3>{n.headline??n.title}</h3><p>{n.summary??n.description}</p><span>{n.publishedAt?date(n.publishedAt):'Publication time unavailable'} · Read briefing</span></a>)}</div></>}
 {tab==='Social'&&<div className="intel-panel"><h2>Official voices, traceable evidence</h2><p>Posts are linked to their originals. An announcement classifier flags candidates; it does not confirm an injury or invent text from inaccessible media.</p>{!detail?.accounts?.length&&<div className="intel-empty">No accounts have been verified yet. Account candidates require corroboration from an official organization website.</div>}{detail?.accounts?.map((a:RecordData)=><a key={a.id} href={a.url} target="_blank" rel="noreferrer">{a.name} · {a.platform} · {a.verified?'Verified':'Verification pending'}</a>)}</div>}
 {tab==='Diagnostics'&&<><AdminControls/><VerificationQueue items={detail?.queue??[]}/><div className="intel-panel"><h2>Administrator diagnostics</h2><p>API-Football: {detail?.budget?.used??0} / 100 daily requests. Sources with unknown permissions stay disabled.</p><p>{data?.counts?.pendingFiles??0} open-data files await incremental import. Catalog availability does not imply complete coverage.</p></div><div className="intel-source-list">{detail?.sources?.map((s:RecordData)=><article key={s.id}><div><h3>{s.name}</h3><a href={s.licenseUrl} target="_blank" rel="noreferrer">Terms & provenance <ArrowUpRight size={12}/></a></div><span className={s.enabled?'intel-status-on':'intel-status-off'}>{s.enabled?'Enabled':'Disabled'}</span><p>{s.disabled_reason??s.notes??s.attribution}</p><small>{s.last_success?`Last success ${new Date(s.last_success).toLocaleString()}`:'No successful request recorded'}{s.last_error?` · ${s.last_error}`:''}</small></article>)}</div></>}
 <footer className="intel-footer"><span className="intel-symbol">P°</span><p>Built on evidence. Open by design.<br/><span>Predictions are estimates, never guarantees. Community fixtures are not an official live feed. Date-only records have no inferred kickoff time.</span></p><a href="/football/classic">Analysis & model details <ArrowUpRight size={15}/></a></footer>
 </main></div>;
}
