'use client';
import {useEffect,useState} from 'react';
import {routeToken} from '@/lib/football/consumer.mjs';
import MatchEvidence from './match-evidence';
type Data=Record<string,any>;
export default function MatchCenter({id}:{id:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch(`/api/intelligence?view=match-context&id=${encodeURIComponent(id)}`);if(!r.ok)throw Error('Match intelligence temporarily unavailable. Please retry.');setData(await r.json());}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[id]);
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'enrich',id})});const result=await r.json() as Data;if(!r.ok)throw Error(result.error);await load();if(result.result?.errors?.length||result.outcomes?.some((o:Data)=>o.error||o.files?.some((f:Data)=>f.error)))setError('Some sources could not refresh. Existing evidence remains available.');}catch(e){setError(String(e));}finally{setBusy(false);}}
 const f=data?.fixture,a=data?.analysis;
 const timeline=(games:Data[])=>games?.length?<div className="match-timeline">{games.map(g=><a key={g.id} href={`/football/match/${encodeURIComponent(g.id)}`}><time>{new Date(g.startsAt).toLocaleDateString()}</time><span>{g.home.name} <b>{g.homeScore} : {g.awayScore}</b> {g.away.name}</span><small>{g.competition.name}</small></a>)}</div>:<p>No earlier meetings are in the imported coverage.</p>;
 return <div className="intel"><main className="match-center"><nav className="match-nav"><a href="/football">P° PitchPredict</a><a href="/football/search">Search</a><a href="/lab">Basketball studio</a></nav>{error&&<p role="alert" className="intel-notice">{error}</p>}{!f?<section className="intel-panel" role="status">{data?.unavailable?'Match not found.':'Loading match intelligence…'}</section>:<>
 <header className="match-hero"><span>{f.competition.name} · {f.label}</span><h1 className="match-score"><a href={`/football/team/${routeToken(f.home.id)}`}>{f.home.name}</a><strong>{f.homeScore??'—'} : {f.awayScore??'—'}</strong><a href={`/football/team/${routeToken(f.away.id)}`}>{f.away.name}</a></h1><p>{new Date(f.startsAt).toLocaleDateString()} · {f.kickoffPrecision==='date'?(f.localKickoff?`Reported local kickoff ${f.localKickoff}; time zone unverified`:'Kickoff time and zone unverified'):new Date(f.startsAt).toLocaleTimeString()} · {typeof f.venue==='string'?f.venue:f.venue?.name??'Venue not supplied by source'}</p><p>Updated {new Date(data!.updatedAt).toLocaleString()} · {data!.completeness}% of tracked evidence categories available</p><button onClick={refresh} disabled={busy}>{busy?'Refreshing permitted sources…':'Refresh Match Intelligence'}</button></header>
 {data!.conflicts?.length>0&&<p className="intel-notice" role="status">Sources disagree on {data!.conflicts.map((c:Data)=>c.field).join(', ')}. Both claims are preserved under Sources and verification.</p>}<section className="intel-panel prediction-center"><h2>Prediction center · {a.label}</h2><p>{a.reason??a.note}</p>{a.probabilities&&<><div className="intel-stats">{['Home','Draw','Away'].map((label,i)=><div key={label}><span>{label}</span><strong>{(a.probabilities[i]*100).toFixed(1)}%</strong></div>)}</div><p>BTTS {(a.btts*100).toFixed(1)}% · Over 2.5 {(a.over25*100).toFixed(1)}% · {a.uncertainty} uncertainty · {a.modelVersion}</p><p>{a.explanations.join(' ')}</p></>}</section>
 <section><h2>Form before this match</h2><p>Cutoff: {new Date(data!.cutoff).toLocaleDateString()}. The analyzed result is excluded.</p><div className="match-columns">{data!.form.map((t:Data)=><article className="intel-panel" key={t.team.id}><h3>{t.team.name}</h3><p>Overall {t.overall.results.join(' · ')||'No earlier results'}</p><p>Home {t.home.results.join(' · ')} · Away {t.away.results.join(' · ')}</p>{timeline(t.fixtures)}</article>)}</div></section>
 <section className="intel-panel"><h2>Head-to-head timeline</h2><p>{data!.h2h.games} earlier meetings · {data!.h2h.homeWins} home-team wins · {data!.h2h.draws} draws · {data!.h2h.awayWins} away-team wins</p>{timeline(data!.h2h.fixtures)}</section>
 <section className="intel-panel"><h2>Standings comparison</h2><p>{data!.table.label}. Cutoff {new Date(data!.table.cutoff).toLocaleDateString()}.</p><div className="table-scroll"><table><thead><tr>{['#','Team','P','W','D','L','GF','GA','GD','Pts'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data!.table.rows.map((r:Data)=><tr key={r.team.id}><td>{r.position}</td><td><a href={`/football/team/${routeToken(r.team.id)}`}>{r.team.name}</a></td>{['played','wins','draws','losses','goalsFor','goalsAgainst','goalDifference','points'].map(k=><td key={k}>{r[k]}</td>)}</tr>)}</tbody></table></div></section>
 {data!.probableLineups?.map((r:Data)=><section className="intel-panel" key={r.team.id}><h2>Probable lineup ? {r.team.name}</h2><p>{r.label} ? {r.matches} recorded team sheets. {r.reason}</p><p>{r.method}. {r.availability}.</p>{r.players.map((p:Data)=><p key={p.id}><a href={`/football/player/${routeToken(p.id)}`}>{p.name}</a> ? {p.position} ? {(p.startingFrequency*100).toFixed(0)}% weighted starting frequency</p>)}</section>)}
 <section className="intel-panel"><h2>Player membership and lineup evidence</h2><p>Membership research as stored today; it may include historical associations and is not a confirmed matchday squad or predicted XI. It is excluded from historical pre-match features.</p><div className="match-columns">{data!.rosters?.map((r:Data)=><article key={r.team.id}><h3>{r.team.name}</h3>{r.players.slice(0,8).map((p:Data)=><p key={p.id}><a href={`/football/player/${routeToken(p.id)}`}>{p.name}</a> ? {p.position??'Position unknown'}</p>)}<a href={`/football/team/${routeToken(r.team.id)}`}>View all {r.players.length} player records ?</a></article>)}</div></section>{['lineups','injuries','fixture_events','fixture_statistics'].map(key=>data!.details[key]?.flat().length>0&&<section className="intel-panel" key={key}><h2>{({lineups:'Recorded team sheets',injuries:'Reported player availability',fixture_events:'Match events',fixture_statistics:'Match statistics'} as Data)[key]}</h2>{data!.details[key].flat().map((r:Data,i:number)=><article key={i}><h3>{typeof r.team==='string'?r.team:r.team?.name}</h3><p>{[r.minute!=null?`${r.minute}?`:null,typeof r.player==='string'?r.player:r.player?.name,r.type,r.detail,r.player?.reason].filter(v=>typeof v==='string').join(' ? ')}</p>{(r.players??r.startXI??[]).filter((p:Data)=>p.started!==false).map((p:Data,j:number)=><p key={j}>{p.name??p.player?.name} {p.jersey??p.player?.number??''}</p>)}{r.shots!=null&&<p>Shots {r.shots} ? Expected goals {Number(r.expectedGoals).toFixed(2)}</p>}{r.statistics?.map((stat:Data,j:number)=><p key={j}>{stat.type}: {stat.value??'Unavailable'}</p>)}</article>)}</section>)}
 <section className="intel-panel"><h2>Lineups, availability and match coverage</h2>{data!.coverage.filter((c:Data)=>!c.available).map((c:Data)=><p key={c.name}><strong>{c.name}:</strong> {c.reason}</p>)}<p>Unknown availability is not evidence that every player is fit. A projected XI needs recorded squad participation.</p></section>
 <details className="intel-panel"><summary>Sources and verification · {data!.sources.length} source records</summary>{data!.sources.map((s:Data)=><p key={s.id}><a href={s.sourceUrl} target="_blank" rel="noreferrer">{s.provider} · original record</a></p>)}<MatchEvidence id={f.id}/></details>
 </>}</main></div>;
}
