'use client';
import {useEffect,useState} from 'react';
import {routeToken} from '@/lib/football/consumer.mjs';
import MarketExplorer from './market-explorer';
import RecommendationDecision from './recommendation-decision';
import ForecastArchive from './forecast-archive';
import MarketAnalysis from './market-analysis';
import TeamBadge from './team-badge';
import PublicNav from './public-nav';
import LocalTime from './local-time';
type Data=Record<string,any>;
export default function MatchCenter({id}:{id:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refreshNote,setRefreshNote]=useState('');
 async function load(){const r=await fetch(`/api/intelligence?view=match-context&id=${encodeURIComponent(id)}`);if(!r.ok)throw Error('Match intelligence temporarily unavailable. Please retry.');setData(await r.json());}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[id]);
 async function refresh(){setBusy(true);setError('');setRefreshNote('Checking available sources and earlier results…');try{const r=await fetch('/api/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'enrich',id})});const result=await r.json() as Data;if(!r.ok)throw Error(result.error);await load();setRefreshNote(result.outcomes?.every((o:Data)=>o.state==='unavailable')?'Cached match intelligence refreshed. Additional details are unavailable from the configured sources.':result.outcomes?.some((o:Data)=>o.state==='deferred'||o.skipped)?'Another update is running. Cached match intelligence is shown; retry shortly.':'Refresh complete. Available records are up to date; missing coverage is listed below.');if(result.result?.errors?.length||result.outcomes?.some((o:Data)=>o.error||o.files?.some((f:Data)=>f.error)))setError('Some sources could not refresh. Existing evidence remains available.');}catch(e){setError(String(e));}finally{setBusy(false);}}
 const f=data?.fixture,a=data?.analysis;
 const timeline=(games:Data[])=>games?.length?<div className="match-timeline">{games.map(g=><a key={g.id} href={`/football/match/${encodeURIComponent(g.id)}`}><time>{new Date(g.startsAt).toLocaleDateString()}</time><span>{g.home.name} <b>{g.homeScore} : {g.awayScore}</b> {g.away.name}</span><small>{g.competition.name}</small></a>)}</div>:<p>No earlier meetings are in the imported coverage.</p>;
 return <div className="intel"><main className="match-center"><PublicNav/>{error&&<p role="alert" className="intel-notice">{error}</p>}{!f?<section className="intel-panel" role="status">{data?.unavailable?'Match not found.':'Loading match intelligence…'}</section>:<>
 <header className="match-hero"><span>{f.competition.name} · {f.label}</span><p>{f.sourceUrl?.match(/\/(20\d{2}-\d{2})\//)?.[1]??f.competition.seasons?.find((s:Data)=>s.id===f.seasonId)?.year??'Season unavailable'} · {f.round??(/quali/i.test(f.competition.name)?'Qualification':'Stage not supplied')}</p><h1 className="match-score"><a href={`/football/team/${routeToken(f.home.id)}`}><TeamBadge id={f.home.id} name={f.home.name} logo={f.home.logo}/>{f.home.name}</a><strong>{f.homeScore??'—'} : {f.awayScore??'—'}</strong><a href={`/football/team/${routeToken(f.away.id)}`}><TeamBadge id={f.away.id} name={f.away.name} logo={f.away.logo}/>{f.away.name}</a></h1><p><LocalTime fixture={f}/> · {typeof f.venue==='string'?f.venue:f.venue?.name??'Venue not supplied by source'}</p><p>Updated {new Date(data!.updatedAt).toLocaleString()}</p><button onClick={refresh} disabled={busy}>{busy?'Refreshing permitted sources…':'Refresh Match Intelligence'}</button>{refreshNote&&<p role="status">{refreshNote}</p>}</header>
 {data!.conflicts?.length>0&&<p className="intel-notice" role="status">Sources disagree on {data!.conflicts.map((c:Data)=>c.field).join(', ')}. Both claims are preserved under Sources and verification.</p>}<section className="intel-panel prediction-center"><h2>Match prediction</h2><p>{a.reason??"Model estimates, not guarantees."}</p>{a.probabilities&&<><div className="intel-stats">{['Home','Draw','Away'].map((label,i)=><div key={label}><span>{label}</span><strong>{(a.probabilities[i]*100).toFixed(1)}%</strong></div>)}</div><details><summary>Model details</summary><p>BTTS {(a.btts*100).toFixed(1)}% · Over 2.5 {(a.over25*100).toFixed(1)}% · {a.uncertainty} uncertainty</p><p>{a.label} · {a.modelVersion}</p><ul>{a.explanations?.slice(0,3).map((reason:string)=><li key={reason}>{reason}</li>)}</ul>{a.asOf&&<p>Estimate saved {new Date(a.asOf).toLocaleString()}. {a.trackingNote}</p>}</details></>}</section>
 {a.statusNotice&&<p className="intel-notice">{a.statusNotice}</p>}{a.archive&&<details><summary>Saved predictions and results</summary><ForecastArchive archive={a.archive}/></details>}
 {data!.recommendation&&<RecommendationDecision decision={data!.recommendation}/>}<details><summary>Explore markets</summary><MarketExplorer analysis={a}/>
 {a.markets&&<MarketAnalysis markets={a.markets}/>}</details><details><summary>Form, head-to-head and standings</summary><section><h2>Form before this match</h2><p>Cutoff: {new Date(data!.cutoff).toLocaleDateString()}. The analyzed result is excluded.</p><div className="match-columns">{data!.form.map((t:Data)=><article className="intel-panel" key={t.team.id}><h3>{t.team.name}</h3><p>Overall {t.overall.results.join(' · ')||'No earlier results'}</p><p>Home {t.home.results.join(' · ')} · Away {t.away.results.join(' · ')}</p>{timeline(t.fixtures)}</article>)}</div></section>
 <section className="intel-panel"><h2>Head-to-head timeline</h2><p>{data!.h2h.games} earlier meetings · {data!.h2h.homeWins} home-team wins · {data!.h2h.draws} draws · {data!.h2h.awayWins} away-team wins</p>{timeline(data!.h2h.fixtures)}</section>
 <section className="intel-panel"><h2>Standings comparison</h2><p>{data!.table.label}. Cutoff {new Date(data!.table.cutoff).toLocaleDateString()}.</p>{data!.table.rows.length>0?<div className="table-scroll"><table><thead><tr>{['#','Team','P','W','D','L','GF','GA','GD','Pts'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data!.table.rows.map((r:Data)=><tr key={r.team.id}><td>{r.position}</td><td><a href={`/football/team/${routeToken(r.team.id)}`}><TeamBadge id={r.team.id} name={r.team.name} logo={r.team.logo}/>{r.team.name}</a></td>{['played','wins','draws','losses','goalsFor','goalsAgainst','goalDifference','points'].map(k=><td key={k}>{r[k]}</td>)}</tr>)}</tbody></table></div>:<p>No completed earlier matches are available for this season. A meaningful pre-match ranking cannot be shown.</p>}</section>
 </details><details><summary>Lineups and player statistics</summary>
 {data!.probableLineups?.filter((r:Data)=>r.players.length>0).map((r:Data)=><section className="intel-panel" key={r.team.id}><h2>{r.label} lineup · {r.team.name}</h2><p>{r.label} · {r.matches?`${r.matches} recorded team sheets.`:''} {r.reason}</p><p>{r.method}. {r.availability}.</p>{r.players.map((p:Data)=><p key={p.id}><a href={`/football/player/${routeToken(p.id)}`}>{p.name}</a> · {p.position} · {p.startingFrequency!=null?`${(p.startingFrequency*100).toFixed(0)}% weighted starting frequency`:''}</p>)}</section>)}
 {['lineups','injuries','fixture_events','fixture_statistics'].map(key=>data!.details[key]?.flat().length>0&&<section className="intel-panel" key={key}><h2>{({lineups:'Recorded team sheets',injuries:'Reported player availability',fixture_events:'Match events',fixture_statistics:'Match statistics'} as Data)[key]}</h2>{data!.details[key].flat().map((r:Data,i:number)=><article key={i}><h3>{typeof r.team==='string'?r.team:r.team?.name}</h3><p>{[r.minute!=null?`${r.minute}?`:null,typeof r.player==='string'?r.player:r.player?.name,r.type,r.detail,r.player?.reason].filter(v=>typeof v==='string').join(' · ')}</p>{(r.players??r.startXI??[]).filter((p:Data)=>p.started!==false).map((p:Data,j:number)=><p key={j}>{p.name??p.player?.name} {p.jersey??p.player?.number??''}</p>)}{r.shots!=null&&<p>Shots {r.shots} · Expected goals {Number(r.expectedGoals).toFixed(2)}</p>}{r.statistics?.map((stat:Data,j:number)=><p key={j}>{stat.type}: {stat.value??'Unavailable'}</p>)}</article>)}</section>)}
 <section className="intel-panel"><h2>Match information</h2><p>{data!.details.lineups?.length?'Confirmed team sheets appear above.':'A confirmed lineup is unavailable for this fixture.'} {data!.details.injuries?.length?'':'Player availability is unverified.'}</p><p>Explore club history: <a href={`/football/team/${routeToken(f.home.id)}`}>{f.home.name}</a> · <a href={`/football/team/${routeToken(f.away.id)}`}>{f.away.name}</a>. Historical membership does not establish a matchday squad.</p></section>
 </details><details><summary>Sources and verification</summary><footer className="intel-panel"><small>Match records: {data!.sources.map((s:Data)=><a key={s.id} href={s.sourceUrl} target="_blank" rel="noreferrer" style={{marginRight:12}}>{s.provider}</a>)} · Badges via TheSportsDB; club marks belong to their owners.</small></footer></details>

 </>}</main></div>;
}
