'use client';
import {useEffect,useState} from 'react';
import {useTimeZone} from './local-time';
export type MatchdayFilters={day:string;from:string;to:string;competition:string;q:string;status:string;tab:string};
const defaults:MatchdayFilters={day:'today',from:'',to:'',competition:'',q:'',status:'',tab:'Predictions'};
export function useMatchday(){const [filters,setFilters]=useState(defaults),[ready,setReady]=useState(false),{zone}=useTimeZone();useEffect(()=>{const read=()=>{let saved={};try{saved=JSON.parse(localStorage.getItem('mnemba-matchday')??'{}');}catch{}const p=new URLSearchParams(location.search),explicit=['day','from','to','competition','q','status'].some(k=>p.has(k));const next={...defaults,...(explicit?{}:saved),...Object.fromEntries(Object.keys(defaults).filter(k=>p.has(k)).map(k=>[k,p.get(k)!]))};if(p.has('from')&&!p.has('day'))next.day='custom';setFilters(next);setReady(true);};void Promise.resolve().then(read);window.addEventListener('popstate',read);return()=>window.removeEventListener('popstate',read);},[]);
 function change(patch:Partial<MatchdayFilters>){const next={...filters,...patch};setFilters(next);const p=new URLSearchParams();for(const [k,v] of Object.entries(next))if(v)p.set(k,v);history.pushState(null,'','/football?'+p);try{localStorage.setItem('mnemba-matchday',JSON.stringify(next));}catch{}}
 const params=new URLSearchParams({...filters,timezone:zone??'UTC'});return{filters,change,ready:ready&&!!zone,query:params.toString()};}
export function MatchdaySelector({filters,change}:{filters:MatchdayFilters;change:(patch:Partial<MatchdayFilters>)=>void}){return <section className="intel-panel matchday-selector" aria-label="Choose matchday"><div className="matchday-presets">{[['yesterday','Yesterday'],['today','Today'],['tomorrow','Tomorrow'],['weekend','This Weekend'],['week','Next 7 Days'],['date','Specific date'],['custom','Custom range']].map(([day,label])=><button key={day} aria-pressed={filters.day===day} onClick={()=>change({day})}>{label}</button>)}</div>{['date','custom'].includes(filters.day)&&<div className="intel-filters"><label>From <input type="date" aria-label="From date" value={filters.from} onChange={e=>change({from:e.target.value})}/></label>{filters.day==='custom'&&<label>To <input type="date" aria-label="To date" value={filters.to} onChange={e=>change({to:e.target.value})}/></label>}</div>}<small>Today follows your timezone. Fixed dates stay fixed in shared links. Weekend means Saturday–Sunday; on Sunday it includes yesterday.</small></section>;}
