import {internalAccess,publicViews,sameOrigin} from '@/lib/football/access.mjs';
import {SourceLifecycle} from '@/lib/football/source-lifecycle.mjs';
import {env} from 'cloudflare:workers';
import {Store} from '@/lib/football/store.mjs';
import {IntelligenceService} from '@/lib/football/intelligence.mjs';
let initialized:Promise<void>|undefined;
async function service(){const bindings=env as unknown as Record<string,any>;const store=new Store(bindings.DB);initialized??=store.init().catch((e:unknown)=>{initialized=undefined;throw e;});await initialized;const instance=new IntelligenceService(store,bindings);await instance.initialize();return instance;}
export async function GET(r:Request){try{const p=new URL(r.url).searchParams;if(!publicViews.has(p.get('view')??'fixtures')&&!internalAccess(r,(env as unknown as Record<string,unknown>).MNEMBA_INTERNAL_TOKEN))return Response.json({error:'Local access required'},{status:403});return Response.json(await(await service()).read(p),{headers:{'Cache-Control':'no-store'}});}catch(e){console.error('intelligence_read',String(e));return Response.json({error:'Database unavailable; check local diagnostics'},{status:503});}}
export async function POST(r:Request){if(r.headers.get('content-type')!=='application/json')return Response.json({error:'Same-origin local JSON request required'},{status:403});try{const body=await r.json() as Record<string,any>;if(!internalAccess(r,(env as unknown as Record<string,unknown>).MNEMBA_INTERNAL_TOKEN)&&!(body.action==='enrich'&&sameOrigin(r)))return Response.json({error:'Internal authorization required'},{status:403});if(body.action==='discover-source')return Response.json(await new SourceLifecycle(await service()).discoverOfficial(body.query));if(body.action==='source-policy'){const instance=await service();if(typeof body.enabled!=='boolean')return Response.json({error:'Boolean enabled required'},{status:400});const source=await instance.store.one('SELECT id FROM source_registry WHERE id=?',String(body.id));if(!source)return Response.json({error:'Unknown source'},{status:404});await instance.store.run('UPDATE source_registry SET user_enabled=? WHERE id=?',Number(body.enabled),source.id);await instance.initialize();return Response.json({source:await instance.store.one('SELECT id,enabled,disabled_reason FROM source_registry WHERE id=?',source.id)});}if(body.action==='enrich'){const instance=await service();return Response.json(await instance.enrichMatch(String(body.id)));}if(body.action==='verify')return Response.json(await(await service()).social.verify(String(body.id),String(body.decision),String(body.reference)));if(!['fixtures','results','catalog','discover','history','reconcile','entities','snapshots','calibration','social','retention','news','archive','identities','backfill','mirrors','search-index','priority-import','model-rollback','models','rosters','documents','badges','players','video-news'].includes(body.job))return Response.json({error:'Unknown job'},{status:400});return Response.json(await(await service()).sync(body.job,body.fileId??''));}catch(e){console.error('intelligence_sync',String(e));return Response.json({error:String(e)},{status:503});}}
