import {form,elo} from './model.mjs';
import {routeToken} from './consumer.mjs';
import {searchText} from './search.mjs';
export async function relatedNews(store,names){const needles=names.map(searchText).filter(n=>n.length>=4),articles=await store.all('SELECT payload FROM news_articles ORDER BY published_at DESC LIMIT 300');return articles.map(r=>JSON.parse(r.payload)).filter(a=>needles.some(n=>(' '+searchText(a.headline+' '+a.summary)+' ').includes(' '+n+' '))).slice(0,12).map(a=>({...a,association:'Text mention; relevance is not confirmation of a match impact'}));}
export async function entityContext(service,id){const s=service.store,team=await s.one('SELECT payload,updated_at FROM football_teams WHERE id=?',id),player=await s.one('SELECT payload,updated_at,team_id FROM football_players WHERE id=?',id),entity=JSON.parse(team?.payload??player?.payload??'null');if(!entity)return{entity:null};
 const aliases=(await s.all('SELECT alias FROM verified_entity_aliases WHERE provider_id=?',id)).map(r=>r.alias),canonical=await s.one('SELECT canonical_id FROM entity_aliases WHERE provider_id=?',id),ids=canonical?(await s.all('SELECT provider_id FROM entity_aliases WHERE canonical_id=?',canonical.canonical_id)).map(r=>r.provider_id):[id],marks=ids.map(()=>'?').join(',');
 if(player){const appearances=(await s.all('SELECT a.payload,f.payload fixture,a.minutes,a.rating FROM football_appearances a JOIN fixtures f ON f.id=a.fixture_id WHERE a.player_id=? AND f.starts_at<? ORDER BY f.starts_at DESC LIMIT 30',id,s.now())).map(r=>({...JSON.parse(r.payload),minutes:r.minutes,rating:r.rating,fixture:JSON.parse(r.fixture)}));const club=await s.one('SELECT name,id FROM football_teams WHERE id=?',entity.teamId??player.team_id??'');return{entity,kind:'player',updatedAt:player.updated_at,appearances,team:club,memberships:(await s.all("SELECT value_json,source_url,confidence FROM field_claims WHERE entity_id=? AND field LIKE 'membership:%' AND valid_to IS NULL AND expires_at>?",id,s.now())).map(r=>({...JSON.parse(r.value_json),confidence:r.confidence})),totals:{appearances:appearances.length,minutes:appearances.reduce((n,a)=>n+(a.minutes??0),0)},news:await relatedNews(s,[entity.name]),fixtures:appearances.map(a=>a.fixture),players:[]};}
 const history=await service.history(id),upcoming=await service.deduplicateFixtures((await s.all(`SELECT payload FROM fixtures WHERE (home_team_id IN (${marks}) OR away_team_id IN (${marks})) AND starts_at>=? ORDER BY starts_at LIMIT 30`,...ids,...ids,s.now())).map(r=>JSON.parse(r.payload))),players=(await s.all(`SELECT DISTINCT p.payload FROM football_players p WHERE p.team_id IN (${marks}) OR p.id IN (SELECT entity_id FROM field_claims WHERE field IN (${marks}) AND valid_to IS NULL AND expires_at>?) ORDER BY p.name`,...ids,...ids.map(id=>'membership:'+id),s.now())).map(r=>JSON.parse(r.payload));
 return{entity,kind:'team',aliases,updatedAt:team.updated_at,form:{overall:form(history,id,s.now()),home:form(history,id,s.now(),'home'),away:form(history,id,s.now(),'away')},rating:elo(history.filter(f=>!f.hasConflict),s.now()).get(id)??null,fixtures:[...upcoming,...history.sort((a,b)=>b.startsAt-a.startsAt).slice(0,20)],players,news:await relatedNews(s,[entity.name,...aliases]),social:canonical?await s.all('SELECT * FROM social_accounts WHERE entity_id=?',canonical.canonical_id):[],competitions:[...new Map([...upcoming,...history].map(f=>[f.competition.id,{...f.competition,url:`/football/competition/${routeToken(f.competition.id)}`}])).values()]};
}
export async function articleContext(store,id){const row=await store.one('SELECT payload,updated_at FROM news_articles WHERE id=?',id);if(!row)return{article:null};const article=JSON.parse(row.payload),text=' '+searchText(article.headline+' '+article.summary)+' ',matches=[];for(const r of await store.all('SELECT id,name FROM football_teams')){const name=searchText(r.name);if(name.length>=4&&text.includes(' '+name+' '))matches.push({...r,url:`/football/team/${routeToken(r.id)}`});}
 const category=article.category??'general',topic=({injuries:'player availability',transfers:'transfer activity',previews:'match preparation',results:'a reported result',general:'football developments'})[category]??'football developments';return{article:{...article,retrievedAt:row.updated_at,relatedTeams:matches.slice(0,8),pitchPredictSummary:`This ${article.publisher} briefing concerns ${topic}${matches.length?' involving '+matches.slice(0,3).map(t=>t.name).join(', '):''}. Its classification is based on the retrieved headline and feed description.`,predictionImpact:category==='injuries'?'Potential availability signal; no adjustment until the affected player, match and status are corroborated.':'No match-specific probability adjustment is justified by this feed excerpt alone.'}};
}
