import {originalAnalysis,scoreDistribution} from './temporal.mjs';
import {dixonColes,fitRho,probabilityMetrics} from './dixon-coles.mjs';
import {digest} from './http.mjs';
const probabilities=cells=>cells.reduce((p,c)=>{p[c.home>c.away?0:c.home===c.away?1:2]+=c.probability;return p;},[0,0,0]);
export class ModelLab{
 constructor(service){this.service=service;this.store=service.store;}
 async trainDependence(competitionId){
  const s=this.store,asOf=s.now(),key=`dc:${competitionId}`,cached=await s.one('SELECT * FROM model_parameters WHERE id=?',key);if(cached&&cached.trained_at>asOf-86400000)return JSON.parse(cached.payload);
  const records=await s.all("SELECT f.payload,c.id evidence_id,c.known_at FROM fixtures f JOIN field_claims c ON c.entity_id=f.id AND c.field='fixture' AND c.valid_to IS NULL AND c.training_allowed=1 WHERE f.competition_id=? AND f.starts_at<? AND f.status IN ('FT','FINISHED','AET','PEN') AND c.known_at<=?",competitionId,asOf,asOf);
  const history=await this.service.deduplicateFixtures(records.map(r=>({...JSON.parse(r.payload),knownAt:r.known_at,evidenceId:r.evidence_id}))),valid=history.filter(f=>!f.hasConflict&&f.homeScore!=null&&f.awayScore!=null);
  // Joint parameter fitting on the training corpus is not a historical forecast/backtest.
  const weight=f=>Math.exp(-(asOf-f.startsAt)/(365*86400000)),total=valid.reduce((n,f)=>n+weight(f),0),lambda=total?valid.reduce((n,f)=>n+weight(f)*f.homeScore,0)/total:1,mu=total?valid.reduce((n,f)=>n+weight(f)*f.awayScore,0)/total:1;
  const fit=fitRho(valid.map(f=>({homeScore:f.homeScore,awayScore:f.awayScore,playedAt:f.startsAt,knownAt:f.knownAt,lambda:Math.max(.1,lambda),mu:Math.max(.1,mu),trainingAllowed:true})),asOf);
  const result={...fit,competitionId,modelVersion:'dc-candidate-1',trainingCutoff:asOf,evidenceIds:valid.map(f=>f.evidenceId),evaluation:'No prospective superiority established. Poisson remains the primary baseline.'};await s.upsert('model_parameters',{id:key,model_version:'dc-candidate-1',trained_at:asOf,training_cutoff:asOf,payload:JSON.stringify(result)});return result;
 }
 async capture(f){
  const s=this.store,asOf=s.now();if(f.startsAt<=asOf||!['NS','TIMED','SCHEDULED'].includes(f.status))return{state:'skipped',reason:'Not a future scheduled fixture'};
  // Date-only source timestamps are ordering placeholders, not trustworthy timed forecast cutoffs.
  if(f.kickoffPrecision==='date')return{state:'abstained',reason:'Verified kickoff instant required for graded forecasts; exploratory analysis remains available.'};
  if(await s.one('SELECT id FROM analysis_forecasts WHERE fixture_id=? AND as_of>?',f.id,asOf-1800000))return{state:'cached'};
  const claims=await s.all("SELECT c.* FROM field_claims c WHERE c.field='fixture' AND c.known_at<=? AND (c.published_at IS NULL OR c.published_at<=?) AND (c.valid_to IS NULL OR c.valid_to>?) AND c.expires_at>?",asOf,asOf,asOf,asOf),fixtureClaim=claims.find(c=>c.entity_id===f.id);if(!fixtureClaim)return{state:'abstained',reason:'No eligible current fixture claim'};
  if(await s.one("SELECT c.id FROM evidence_conflicts c JOIN fixture_identities i ON i.canonical_id=c.entity_id WHERE i.fixture_id=? AND c.status='open'",f.id))return{state:'abstained',reason:'Unresolved fixture claims'};
  const knownFixture=JSON.parse(fixtureClaim.value_json);if(knownFixture.startsAt!==f.startsAt)return{state:'abstained',reason:'Kickoff conflict'};
  const history=await this.service.deduplicateFixtures(claims.map(c=>JSON.parse(c.value_json)).filter(g=>g.startsAt<asOf&&g.startsAt<f.startsAt));const analysis=originalAnalysis(knownFixture,history,{asOf});if(!analysis.probabilities)return{state:'abstained',reason:analysis.reason};
  const usedIds=new Set(history.map(g=>g.id)),used=claims.filter(c=>c.entity_id===f.id||usedIds.has(c.entity_id)),maxKnownAt=Math.max(...used.map(c=>c.known_at)),trainingAllowed=used.every(c=>c.training_allowed===1);
  const fit=await this.trainDependence(f.competition.id),[lambda,mu]=analysis.expectedGoals,rho=Math.min(Math.min(1/(lambda*mu),1)-1e-8,Math.max(Math.max(-1/lambda,-1/mu)+1e-8,fit.rho)),candidate=dixonColes(scoreDistribution(lambda,mu),lambda,mu,rho);
  const versions=[{...analysis,modelVersion:'poisson-temporal-1'},{...analysis,modelVersion:'dc-candidate-1',probabilities:probabilities(candidate),distribution:candidate.sort((a,b)=>b.probability-a.probability).slice(0,16),rho,parameterStatus:fit.status,calibrated:false,note:fit.evaluation}];
  for(const payload of versions){const id=await digest([f.id,payload.modelVersion,asOf]);await s.run('INSERT OR IGNORE INTO analysis_forecasts(id,fixture_id,model_version,as_of,kickoff_at,max_known_at,training_allowed,payload,evidence_ids) VALUES(?,?,?,?,?,?,?,?,?)',id,f.id,payload.modelVersion,asOf,f.startsAt,maxKnownAt,Number(trainingAllowed),JSON.stringify({...payload,competitionId:f.competition.id,asOf}),JSON.stringify(used.map(c=>c.id)));}
  return{state:'captured',forecasts:versions.length};
 }
 async update(){const rows=await this.store.all("SELECT payload FROM fixtures WHERE starts_at>? AND starts_at<? AND status IN ('NS','TIMED','SCHEDULED') ORDER BY starts_at LIMIT 150",this.store.now(),this.store.now()+8*86400000);const outcomes={captured:0,cached:0,abstained:0,skipped:0};for(const r of await this.service.deduplicateFixtures(rows.map(r=>JSON.parse(r.payload)))){const result=await this.capture(r);outcomes[result.state]++;}const competitions=[...new Set(rows.map(r=>JSON.parse(r.payload).competition.id))].slice(0,12);let trained=0;for(const competition of competitions)if((await this.trainDependence(competition)).status==='trained-candidate')trained++;return{...outcomes,trained,graded:await this.grade()};}
 async grade(){let count=0;const rows=await this.store.all("SELECT p.*,f.payload fixture,f.updated_at result_known_at FROM analysis_forecasts p JOIN fixtures f ON f.id=p.fixture_id LEFT JOIN analysis_grades g ON g.id=p.id WHERE g.id IS NULL AND f.status IN ('FT','FINISHED','AET','PEN') AND f.starts_at=p.kickoff_at");for(const row of rows){const f=JSON.parse(row.fixture);if(f.homeScore==null||f.awayScore==null)continue;const conflict=await this.store.one("SELECT c.id FROM evidence_conflicts c JOIN fixture_identities i ON i.canonical_id=c.entity_id WHERE i.fixture_id=? AND c.status='open' AND c.field IN ('homeScore','awayScore','startsAt')",row.fixture_id);if(conflict)continue;const outcome=f.homeScore>f.awayScore?0:f.homeScore===f.awayScore?1:2;await this.store.upsert('analysis_grades',{id:row.id,fixture_id:row.fixture_id,result_known_at:row.result_known_at,outcome,payload:JSON.stringify({homeScore:f.homeScore,awayScore:f.awayScore,sourceUrl:f.sourceUrl})});count++;}return count;}
 async performance(){const rows=await this.store.all('SELECT p.*,g.outcome,g.result_known_at FROM analysis_forecasts p JOIN analysis_grades g ON g.id=p.id ORDER BY p.as_of'),versions=[];
  for(const version of ['poisson-temporal-1','dc-candidate-1']){const unique=new Map();for(const r of rows.filter(r=>r.model_version===version)){if(r.as_of<r.kickoff_at&&r.max_known_at<=r.as_of)unique.set(r.fixture_id,r);}const data=[...unique.values()].map(r=>({...JSON.parse(r.payload),outcome:r.outcome,fixtureId:r.fixture_id})),groups={};for(const r of data){(groups[r.competitionId]??=[]).push(r);}versions.push({version,...probabilityMetrics(data),byCompetition:Object.fromEntries(Object.entries(groups).map(([k,v])=>[k,probabilityMetrics(v)])),uniformBaseline:probabilityMetrics(data.map(r=>({...r,probabilities:[1/3,1/3,1/3]})))});}
  return{versions,forecasts:(await this.store.one('SELECT COUNT(*) n FROM analysis_forecasts')).n,parameters:(await this.store.all('SELECT payload FROM model_parameters')).map(r=>{const {evidenceIds,...summary}=JSON.parse(r.payload);return summary;}),note:'Prospective immutable forecasts only; latest forecast per fixture/version. No reconstructed historical prediction is counted.'};
 }
}
