import {scoreDistribution} from './temporal.mjs';
import {marketOptions,priceMarket,MARKET_SCOPE,settleMarket} from './market-registry.mjs';
import {matchState,analysisCutoff} from './match-state.mjs';
import {savedEstimate} from './estimates.mjs';
import {priorityFor} from './priority-coverage.mjs';
import {matchdayRange,inMatchday} from './matchday.mjs';
import {digest} from './http.mjs';
export const RULE_VERSION='matchday-preference-1';
export function decideRecommendation(f,a,now=Date.now()){
 const base={decision:'No strong selection',ruleVersion:RULE_VERSION,scope:MARKET_SCOPE,primary:null,alternatives:[],note:'Provisional model preference, not measured accuracy or betting value. All selections can lose. Lineup context is not a numeric input.'};
 if(!matchState(f,now).previewAllowed)return{...base,reason:'Already started or not scheduled. Review the saved pre-match record; no in-play model is offered.'};
 if(f.hasConflict||!a?.probabilities||!a.expectedGoals)return{...base,reason:a?.reason??'Conflicting or insufficient earlier results.'};
 if(priorityFor(f.competition)?.gender==='women'||/u.?\d{2}|women/i.test(f.competition.name))return{...base,reason:'No validated model for this age/gender category; club-league parameters are not transferred.'};
 const sample=Math.min(a.factors?.home?.games??0,a.factors?.away?.games??0),rest=Math.max(a.factors?.home?.restDays??Infinity,a.factors?.away?.restDays??Infinity);
 if(sample<8||rest>90)return{...base,reason:'Require at least eight earlier matches per team and participation within 90 days.',sample};
 const cells=scoreDistribution(...a.expectedGoals),options=marketOptions().filter(o=>o.market==='result'||o.market==='btts'||o.market==='total'&&o.side==='both'&&o.line===2.5).map(o=>({...o,probabilities:priceMarket(cells,o)})).sort((a,b)=>b.probabilities.win-a.probabilities.win||JSON.stringify(a).localeCompare(JSON.stringify(b))),eligible=options.filter(o=>o.probabilities.win>=.6&&o.probabilities.win<=.85);
 if(!eligible.length)return{...base,reason:'None of the balanced 1X2, BTTS or 2.5-goal options meets the 60–85% provisional probability range.',sample};
 return{...base,decision:'Provisional model preference',primary:eligible[0],alternatives:eligible.slice(1,3),sample,rank:Math.round((eligible[0].probabilities.win-.5)*10000)+sample*10-Math.round(rest),reason:'Highest estimated win probability among eligible 1X2, BTTS and match 2.5-goal options; broad safety lines are excluded.',reasons:a.explanations?.slice(0,2)??[],uncertainty:f.kickoffPrecision==='date'?'Kickoff time unverified; this preview is excluded from tracked accuracy.':'Uncalibrated results/form baseline; confirmed availability may change.',createdAt:a.asOf??now,modelVersion:a.modelVersion};
}
export function rankRecommendations(entries){return entries.filter(e=>e.recommendation.primary).sort((a,b)=>b.recommendation.rank-a.recommendation.rank||a.fixture.id.localeCompare(b.fixture.id)).filter((e,i,all)=>all.findIndex(x=>(x.fixture.canonicalId??x.fixture.id)===(e.fixture.canonicalId??e.fixture.id))===i).slice(0,5);}
export async function matchdayView(service,params){
 const s=service.store,range=matchdayRange(params,s.now()),competition=params.get('competition')??'',q=(params.get('q')??'').toLowerCase(),status=params.get('status')??'';
 const scopeKey=JSON.stringify([range.from,range.to,range.zone,competition,q,status]),cacheKey='matchday:'+await digest(scopeKey),cached=await s.cache(cacheKey);if(cached&&!cached.stale)return cached.data;
 const owner=await s.lock(cacheKey,120000);if(!owner)return cached?{...cached.data,refreshing:true}:{range,fixtures:[],count:0,picks:[],loading:true,note:'Preparing this matchday. Please retry shortly.'};
 try{
 const raw=await s.all("SELECT payload FROM fixtures WHERE starts_at>=? AND starts_at<?",Math.min(range.start,Date.parse(range.from)),Math.max(range.end,Date.parse(range.to)+86400000));
 const fixtures=(await service.deduplicateFixtures(raw.map(r=>JSON.parse(r.payload)))).filter(f=>inMatchday(f,range)&&(!competition||competition.split(',').includes(f.competition.id)||competition===priorityFor(f.competition)?.id)&&(!q||`${f.home.name} ${f.away.name}`.toLowerCase().includes(q))&&(!status||f.status===status));
 const entries=[];for(const f of fixtures.filter(f=>priorityFor(f.competition)&&matchState(f,s.now()).previewAllowed)){const history=await service.history(f.home.id,f.away.id,analysisCutoff(f,s.now()),f.id),analysis=await savedEstimate(service,f,history);entries.push({fixture:f,analysis,recommendation:decideRecommendation(f,analysis,s.now())});}
 const picks=rankRecommendations(entries),original=await s.one('SELECT id,payload,published_at FROM recommendation_lists WHERE scope_key=? ORDER BY published_at LIMIT 1',scopeKey),previous=await s.one('SELECT payload FROM recommendation_lists WHERE scope_key=? ORDER BY published_at DESC LIMIT 1',scopeKey);
 const selection=picks.map(e=>({fixtureId:e.fixture.id,canonicalId:e.fixture.canonicalId??e.fixture.id,kickoff:e.fixture.startsAt,tracked:matchState(e.fixture,s.now()).forecastEligible,forecastId:e.analysis.archive?.selected?.id??null,home:e.fixture.home.name,away:e.fixture.away.name,recommendation:e.recommendation,evidence:e.analysis.factors,modelVersion:e.analysis.modelVersion}));
 const signature=JSON.stringify(selection.map(e=>[e.fixtureId,e.forecastId,e.recommendation.primary,e.modelVersion]));let publicationId=null;
 if(selection.length&&(!previous||JSON.parse(previous.payload).signature!==signature)){publicationId=await digest([scopeKey,s.now(),signature]);await s.run('INSERT OR IGNORE INTO recommendation_lists(id,scope_key,published_at,rule_version,payload) VALUES(?,?,?,?,?)',publicationId,scopeKey,s.now(),RULE_VERSION,JSON.stringify({range,signature,selection,scope:scopeKey}));}
 const result={range,fixtures,count:fixtures.length,eligible:entries.filter(e=>e.recommendation.primary).length,picks,publicationId,original:original?{id:original.id,publishedAt:original.published_at,...JSON.parse(original.payload)}:null,note:picks.length<5?`${picks.length} supported provisional selections in this range. No other dates or weaker options were added.`:'Five strongest supported provisional selections. Model probabilities are not a proven hit rate.',updatedAt:s.now()};await s.putCache(cacheKey,result,60000);return result;
 }finally{await s.unlock(cacheKey,owner);}
}
export async function gradeRecommendations(service){const s=service.store,lists=await s.all('SELECT * FROM recommendation_lists');let count=0;
 for(const list of lists)for(const pick of JSON.parse(list.payload).selection){const row=await s.one('SELECT payload FROM fixtures WHERE id=?',pick.fixtureId);if(!row)continue;const f=JSON.parse(row.payload),state=matchState(f,s.now());let settlement='pending',reason='Awaiting regulation result';
 const conflict=await s.one("SELECT c.id FROM evidence_conflicts c JOIN fixture_identities i ON i.canonical_id=c.entity_id WHERE i.fixture_id=? AND c.status='open'",f.id);
 if(!pick.tracked){settlement='excluded';reason='Date-only or unverified pre-kickoff timing; exploratory record';}else if(conflict){reason='Conflicting result; pending verification';}else if(f.startsAt!==pick.kickoff||state.state==='cancelled'){settlement='void';reason='Cancelled or rescheduled';}else if(state.state==='completed'){const score=['FT','FINISHED'].includes(f.status)?[f.homeScore,f.awayScore]:f.regulationScore?[f.regulationScore.home,f.regulationScore.away]:[];settlement=settleMarket(pick.recommendation.primary,...score);reason='Regulation-time settlement; extra-time/shootout totals excluded';}
 const payload=JSON.stringify({settlement,reason,homeScore:f.homeScore,awayScore:f.awayScore}),old=await s.one('SELECT id,payload FROM recommendation_grades WHERE list_id=? AND fixture_id=? ORDER BY recorded_at DESC,rowid DESC LIMIT 1',list.id,f.id);if(old?.payload===payload)continue;
 await s.run('INSERT INTO recommendation_grades(id,list_id,fixture_id,recorded_at,payload) VALUES(?,?,?,?,?)',await digest([list.id,f.id,payload,old?.id]),list.id,f.id,s.now(),payload);count++;
 }return count;
}
export async function shortlistHistory(service,params){const offset=Math.max(0,Number(params.get('offset'))||0),rows=await service.store.all('SELECT * FROM recommendation_lists ORDER BY published_at DESC LIMIT 21 OFFSET ?',offset),lists=[];for(const row of rows.slice(0,20)){const payload=JSON.parse(row.payload);for(const p of payload.selection){const grade=await service.store.one('SELECT payload FROM recommendation_grades WHERE list_id=? AND fixture_id=? ORDER BY recorded_at DESC,rowid DESC LIMIT 1',row.id,p.fixtureId);p.grade=grade?JSON.parse(grade.payload):{settlement:'pending'};}lists.push({id:row.id,publishedAt:row.published_at,ruleVersion:row.rule_version,...payload,signature:undefined});}return{lists,nextOffset:rows.length>20?offset+20:null,note:'All published versions remain, including losses. Date-only previews are excluded from measured accuracy. No selection-process hit rate is established.'};}
