import {dayBounds} from './timezone.mjs';
import {competitionLabel} from './competition-catalog.mjs';
import {routeToken} from './consumer.mjs';
export const searchText=value=>String(value??'').normalize('NFKD').replace(/\p{M}/gu,'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();
export function editDistance(a,b){if(Math.abs(a.length-b.length)>2)return 3;let previous=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const next=[i];for(let j=1;j<=b.length;j++)next[j]=Math.min(next[j-1]+1,previous[j]+1,previous[j-1]+Number(a[i-1]!==b[j-1]));previous=next;}return previous[b.length];}
export async function refreshSearchIndex(store,force=false){
 const cached=await store.cache('search-index');if(!force&&cached&&!cached.stale)return cached.data;
 const owner=await store.lock('search-index',120000);if(!owner)return{state:'updating'};
 try{
 const old=new Map((await store.all('SELECT id,revision FROM search_documents')).map(r=>[r.id,r.revision])),documents=[];
 const aliases=new Map();for(const r of await store.all('SELECT provider_id,alias FROM verified_entity_aliases')){if(!aliases.has(r.provider_id))aliases.set(r.provider_id,[]);aliases.get(r.provider_id).push(r.alias);}
 for(const [table,kind] of [['football_teams','team'],['football_players','player'],['competitions','competition'],['countries','country']]){
  for(const row of await store.all(`SELECT id,name,payload,updated_at FROM ${table}`)){const p=JSON.parse(row.payload);documents.push({id:row.id,kind,name:row.name,aliases:[...(p.aliases??[]),...(aliases.get(row.id)??[]),...(kind==='competition'?[competitionLabel(p)]:[])],country:typeof p.country==='object'?p.country?.name:p.country,description:p.description??null,position:p.position??null,birthDate:p.birthDate??null,team:p.teamId??null,competition:kind==='competition'?row.id:null,url:kind==='country'?`/football/search?country=${encodeURIComponent(row.name)}`:`/football/${kind}/${routeToken(row.id)}`,revision:row.updated_at});}
 }
 const fixtures=await store.all("SELECT f.id,f.payload,f.updated_at FROM fixtures f LEFT JOIN fixture_identities i ON i.fixture_id=f.id GROUP BY COALESCE(i.canonical_id,f.id)");
 for(const row of fixtures){const f=JSON.parse(row.payload);documents.push({id:f.id,kind:'fixture',name:`${f.home.name} vs ${f.away.name}`,aliases:[...(aliases.get(f.home.id)??[]),...(aliases.get(f.away.id)??[])],country:f.competition.country?.name,competition:f.competition.id,season:f.seasonId,team:[f.home.id,f.away.id],date:f.startsAt,kickoffPrecision:f.kickoffPrecision,status:f.status,url:`/football/match/${encodeURIComponent(f.id)}`,revision:row.updated_at});}
 for(const row of await store.all('SELECT id,headline,published_at,updated_at FROM news_articles'))documents.push({id:row.id,kind:'news',name:row.headline,date:row.published_at,url:`/football/news/${routeToken(row.id)}`,revision:row.updated_at});
 for(const row of await store.all('SELECT p.id,p.fixture_id,p.created_at,f.payload FROM model_predictions p JOIN fixtures f ON f.id=p.fixture_id WHERE f.starts_at>? GROUP BY p.fixture_id',store.now())){const f=JSON.parse(row.payload);documents.push({id:row.id,kind:'prediction',name:`${f.home.name} vs ${f.away.name} prediction`,country:f.competition.country?.name,competition:f.competition.id,team:[f.home.id,f.away.id],date:f.startsAt,kickoffPrecision:f.kickoffPrecision,status:f.status,url:`/football/match/${encodeURIComponent(f.id)}`,revision:row.created_at});}
 const statements=[],present=new Set();let updated=0;
 for(const d of documents){const id=d.kind+':'+d.id;present.add(id);const revision=JSON.stringify([d.revision,d.aliases,d.position,d.description,d.birthDate]);if(old.get(id)===revision)continue;updated++;const normalized=searchText(d.name+' '+(d.aliases??[]).join(' '));statements.push(['INSERT INTO search_documents(id,entity_id,kind,name,normalized,payload,revision) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,normalized=excluded.normalized,payload=excluded.payload,revision=excluded.revision',id,d.id,d.kind,d.name,normalized,JSON.stringify(d),revision],['DELETE FROM search_words WHERE document_id=?',id]);for(const word of new Set(normalized.split(' ').filter(Boolean)))statements.push(['INSERT OR IGNORE INTO search_words(word,document_id) VALUES(?,?)',word,id]);}
 for(const id of old.keys())if(!present.has(id))statements.push(['DELETE FROM search_documents WHERE id=?',id]);await store.batch(statements);const result={state:'ready',documents:documents.length,updated};await store.putCache('search-index',result,300000);return result;
 }finally{await store.unlock('search-index',owner);}
}
export async function globalSearch(store,params){
 await refreshSearchIndex(store);const q=searchText((params.get('q')??'').slice(0,100)),words=q.split(' ').filter(Boolean),kind=params.get('kind'),country=params.get('country'),competition=params.get('competition'),season=params.get('season'),team=params.get('team'),status=params.get('status'),sport=params.get('sport')??'football';
 if(!['football','soccer'].includes(sport))return{results:[],total:0,reason:'Basketball model scenarios are available in the Demo Data studio; no production basketball index is configured.'};
 if(q.length<2&&!kind&&!country&&!competition&&!team&&!status)return{results:[],total:0};
 const clauses=[],args=[];if(words.length&&!params.has('_fuzzyAll')){const prefix=words.slice().sort((a,b)=>b.length-a.length)[0].slice(0,2);clauses.push('id IN (SELECT document_id FROM search_words WHERE word>=? AND word<?)');args.push(prefix,prefix+'\uffff');}
 if(kind){clauses.push('kind=?');args.push(kind);}let candidates=await store.all(`SELECT payload,normalized FROM search_documents ${clauses.length?'WHERE '+clauses.join(' AND '):''} LIMIT 10000`,...args);
 const ranked=[];for(const row of candidates){const d=JSON.parse(row.payload),tokens=row.normalized.split(' ');if(country&&searchText(d.country)!==searchText(country)||competition&&!competition.split(',').includes(d.competition)||season&&d.season!==season||team&&!(Array.isArray(d.team)?d.team:[d.team]).includes(team)||status&&d.status!==status)continue;if(params.get('from')&&!(d.date>=(d.kickoffPrecision==='date'?Date.parse(params.get('from')):dayBounds(params.get('from'),params.get('timezone')??'UTC').start)))continue;if(params.get('to')&&!(d.date<(d.kickoffPrecision==='date'?Date.parse(params.get('to'))+86400000:dayBounds(params.get('to'),params.get('timezone')??'UTC').end)))continue;
 let cost=0;for(const word of words){const distance=Math.min(...tokens.map(t=>t.startsWith(word)?0:editDistance(word,t)));if(distance>(word.length>=7?2:word.length>=4?1:0)){cost=Infinity;break;}cost+=distance;}if(!Number.isFinite(cost))continue;
 const exact=searchText(d.name)===q||d.aliases?.some(a=>searchText(a)===q);ranked.push({...d,rank:cost*100+(exact?0:10)+({team:0,player:1,competition:2,country:3,fixture:4,prediction:5,news:6})[d.kind]});}
 if(!ranked.length&&q.length>=4&&!params.has('_fuzzyAll')){const retry=new URLSearchParams(params);retry.set('_fuzzyAll','1');return globalSearch(store,retry);}
 ranked.sort((a,b)=>a.rank-b.rank||(b.date??0)-(a.date??0)||a.name.localeCompare(b.name));const offset=Math.min(10000,Math.max(0,Math.trunc(Number(params.get('offset'))||0))),limit=30;return{results:ranked.slice(offset,offset+limit),total:ranked.length,nextOffset:offset+limit<ranked.length?offset+limit:null,capped:candidates.length===10000};
}
