import {cleanText} from './news.mjs';
import {safeVideo} from './media.mjs';
export const CLUB_VIDEO_FEED='https://www.youtube.com/feeds/videos.xml?channel_id=UC14UlmYlSNiQCBe9Eookf_A';
export function videoEntries(xml,now){
 if(xml.length>1000000||/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('Unsafe video feed');
 const tag=(block,name)=>block.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`))?.[1]??'';
 return [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)].map(([,b])=>({videoId:cleanText(tag(b,'yt:videoId')),headline:cleanText(tag(b,'title')).slice(0,300),summary:cleanText(tag(b,'media:description').split('\n').filter(line=>!(/subscribe|join|member|https?:|www\.|follow|official app/i.test(line))).slice(0,3).join(' ')).slice(0,280),publishedAt:Date.parse(tag(b,'published')),channel:cleanText(tag(b,'yt:channelId'))})).filter(v=>v.headline&&/^[\w-]{11}$/.test(v.videoId)&&v.channel.replace(/^UC/,'')==='14UlmYlSNiQCBe9Eookf_A'&&v.publishedAt<=now&&now-v.publishedAt<7*86400000).slice(0,3);
}
export async function syncVideoNews(service){const s=service.store,response=await service.http.request('club-video-feed',CLUB_VIDEO_FEED);if(!response.ok)throw Error('Club video feed unavailable');const videos=videoEntries(await response.text(),s.now()),results=[];
 for(const v of videos){const url='https://www.youtube.com/watch?v='+v.videoId;try{const metadata=await service.http.json('club-video-feed','https://www.youtube.com/oembed?'+new URLSearchParams({url,format:'json'}));if(metadata.author_name!=='FC Barcelona'||!safeVideo(url)||!metadata.html?.includes('/embed/'+v.videoId))throw Error('Publisher or embed permission not verified');const payload={id:url,url,headline:v.headline,summary:v.summary||'FC Barcelona published this video on its official channel. Watch the publisher’s clip below; no transcript or additional account was supplied.',publisher:'FC Barcelona',publishedAt:v.publishedAt,category:'general',label:'Publisher video',summaryLabel:'Publisher description',relatedClubName:'FC Barcelona',media:{url,articleUrl:url,permission:'publisher-embed',verifiedAt:s.now(),channelUrl:'https://www.youtube.com/@FCBarcelona',verificationUrl:'https://www.fcbarcelona.com/en/club/news/4340606/barca-surpasses-fifa-and-the-nba-reaching-238-million-subscriptions-on-youtube'}};
 await s.upsert('news_articles',{id:url,canonical_url:url,headline:v.headline,publisher:payload.publisher,published_at:v.publishedAt,category:'general',payload:JSON.stringify(payload),updated_at:s.now()});results.push({id:url,state:'imported'});}catch(e){results.push({id:url,error:e.message});}}
 return{videos:results,imported:results.filter(r=>r.state==='imported').length,errors:results.filter(r=>r.error).map(r=>r.error)};
}
