import { DatabaseSync } from 'node:sqlite';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createPool, translateSQL } from '../../lib/azure/postgres.mjs';

const [source, schema, reportPath] = process.argv.slice(2);
if (!source || !/^[a-z][a-z0-9_]{0,40}$/.test(schema ?? '') || !reportPath)
  throw new Error('Usage: node scripts/azure/migrate.mjs BACKUP.sqlite NEW_SCHEMA REPORT.json (DATABASE_URL from environment)');
const rowidTables = new Set(['analysis_grade_audit', 'recommendation_grades']);
const quote = name => '"' + name.replaceAll('"', '""') + '"';
const sqlite = new DatabaseSync(source, { readOnly: true });
const integrity = sqlite.prepare('PRAGMA integrity_check').all();
if (integrity.some(row => row.integrity_check !== 'ok')) throw new Error('Source integrity check failed');
const violations = sqlite.prepare('PRAGMA foreign_key_check').all();
if (violations.length) throw new Error(`Source has ${violations.length} foreign key violations; do not silently discard records`);
const tables = sqlite.prepare("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_cf_%' AND name!='d1_migrations' ORDER BY name").all();
const pool = createPool(), client = await pool.connect();
const report = { source, schema, sourceSha256: createHash('sha256').update(readFileSync(source)).digest('hex'), startedAt: new Date().toISOString(), tables: [], verified: false };
function digest(rows) { return createHash('sha256').update(JSON.stringify(rows)).digest('hex'); }
try {
  await client.query('BEGIN');
  // A replay verifies the committed snapshot instead of duplicating records.
  const existing = await client.query('SELECT schema_name FROM information_schema.schemata WHERE schema_name=$1', [schema]);
  if (existing.rowCount) {
    const prior = (await client.query(`SELECT payload FROM ${quote(schema)}._mnemba_migration WHERE id=1`)).rows[0]?.payload;
    if (!prior || prior.sourceSha256 !== report.sourceSha256) throw new Error('Existing schema belongs to a different snapshot');
    for (const table of prior.tables) {
      const columns = (await client.query('SELECT column_name FROM information_schema.columns WHERE table_schema=$1 AND table_name=$2 ORDER BY ordinal_position', [schema, table.name])).rows.map(c => c.column_name);
      const rows = (await client.query(`SELECT * FROM ${quote(schema)}.${quote(table.name)}`)).rows;
      const checksum = digest(rows.map(row => digest(columns.map(key => row[key]))).sort());
      if (rows.length !== table.sourceCount || checksum !== table.sha256) throw new Error('Replay verification failed: ' + table.name);
    }
    await client.query('COMMIT');
    writeFileSync(reportPath, JSON.stringify({...prior, replayVerifiedAt: new Date().toISOString()}, null, 2), {mode: 0o600});
    console.log('PASS replay: existing snapshot matches every count and content hash');
  } else {
  await client.query(`CREATE SCHEMA ${quote(schema)}`);
  await client.query(`SET LOCAL search_path TO ${quote(schema)},public`);
  await client.query('SET LOCAL statement_timeout=0');
  const remaining = [...tables], created = new Set();
  while (remaining.length) {
    const index = remaining.findIndex(t => sqlite.prepare(`PRAGMA foreign_key_list(${quote(t.name)})`).all().every(f => f.table === t.name || created.has(f.table)));
    if (index < 0) throw new Error('Cyclic foreign keys require an explicit migration');
    const [table] = remaining.splice(index, 1);
    let ddl = translateSQL(table.sql).replace(/BIGINT PRIMARY KEY AUTOINCREMENT/gi, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY').replace(/DEFAULT false/gi, 'DEFAULT 0').replace(/DEFAULT true/gi, 'DEFAULT 1');
    // SQLite permits fractional minutes in an INTEGER column. Preserve them.
    if (table.name === 'football_appearances') ddl = ddl.replace(/\bminutes BIGINT/i, 'minutes DOUBLE PRECISION');
    await client.query(ddl);
    if (rowidTables.has(table.name)) await client.query(`ALTER TABLE ${quote(table.name)} ADD COLUMN _sqlite_rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE`);
    created.add(table.name);
  }
  // SQLite uniqueness constraints are needed for ON CONFLICT in runtime queries.
  for (const table of tables) {
    const indexes = sqlite.prepare(`PRAGMA index_list(${quote(table.name)})`).all();
    for (const index of indexes) {
      if (index.origin === 'pk' || index.origin === 'u') continue; // already in CREATE TABLE
      const record = sqlite.prepare('SELECT sql FROM sqlite_master WHERE type=\'index\' AND name=?').get(index.name);
      if (record?.sql) await client.query(translateSQL(record.sql));
    }
  }
  // Preserve parent order for inserts as well as definitions.
  for (const name of created) {
    const columns = sqlite.prepare(`PRAGMA table_info(${quote(name)})`).all();
    if (rowidTables.has(name)) columns.push({ name: '_sqlite_rowid', pk: 0 });
    const keys = columns.map(c => c.name), primary = columns.filter(c => c.pk).sort((a,b) => a.pk-b.pk).map(c => c.name);
    const order = (primary.length ? primary : keys).map(quote).join(',');
    const select = `SELECT ${keys.map(quote).join(',')} FROM ${quote(name)} ORDER BY ${order}`;
    const sourceSelect = rowidTables.has(name) ? select.replace('"_sqlite_rowid"', 'rowid AS _sqlite_rowid') : select;
    const rows = sqlite.prepare(sourceSelect).all();
    for (let offset = 0; offset < rows.length; offset += 200) {
      const chunk = rows.slice(offset, offset + 200), values = [];
      const placeholders = chunk.map(row => '(' + keys.map(key => { values.push(row[key]); return '$'+values.length; }).join(',') + ')').join(',');
      await client.query(`INSERT INTO ${quote(name)} (${keys.map(quote).join(',')}) VALUES ${placeholders}`, values);
    }
    const target = (await client.query(select)).rows;
    // Compare row-content hashes independent of database collation ordering.
    const canonical = records => records.map(row => digest(keys.map(key => row[key]))).sort();
    const sourceHash = digest(canonical(rows)), targetHash = digest(canonical(target));
    if (rows.length !== target.length || sourceHash !== targetHash) throw new Error(`Verification failed: ${name}`);
    for (const column of columns) {
      const sequence = (await client.query('SELECT pg_get_serial_sequence($1,$2) AS name', [`${schema}.${name}`, column.name])).rows[0].name;
      if (sequence) await client.query(`SELECT setval($1, COALESCE((SELECT MAX(${quote(column.name)}) FROM ${quote(name)}),1), EXISTS(SELECT 1 FROM ${quote(name)}))`, [sequence]);
    }
    report.tables.push({ name, sourceCount: rows.length, targetCount: target.length, sha256: sourceHash });
    console.log(`${name}: ${rows.length} records verified`);
  }
  const triggers = sqlite.prepare("SELECT name,tbl_name,sql FROM sqlite_master WHERE type='trigger'").all();
  await client.query(`CREATE FUNCTION reject_immutable_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Immutable historical record'; END $$`);
  for (const trigger of triggers) {
    const match = trigger.sql.match(/BEFORE (UPDATE|DELETE) ON \w+ BEGIN SELECT RAISE\(ABORT,'[^']*'\); END/i);
    if (!match) throw new Error('Unsupported source trigger: ' + trigger.name);
    await client.query(`CREATE TRIGGER ${quote(trigger.name)} BEFORE ${match[1]} ON ${quote(trigger.tbl_name)} FOR EACH ROW EXECUTE FUNCTION reject_immutable_change()`);
  }
  report.triggers = triggers.map(t => t.name);
  report.verified = true; report.finishedAt = new Date().toISOString();
  await client.query('CREATE TABLE _mnemba_migration (id INTEGER PRIMARY KEY, payload JSONB NOT NULL)');
  await client.query('INSERT INTO _mnemba_migration VALUES(1,$1)', [JSON.stringify(report)]);
  await client.query('COMMIT');
  writeFileSync(reportPath, JSON.stringify(report, null, 2), { mode: 0o600 });
  }
} catch (error) {
  await client.query('ROLLBACK');
  // SQL driver errors can contain record values; avoid printing them.
  console.error('Migration rolled back:', error.code ?? error.message);
  process.exitCode = 1;
} finally { sqlite.close(); client.release(); await pool.end(); }
