import {populatedLocalDatabase} from './local-database.mjs';
import {localOrigin} from './local-origin.mjs';
// Local app journeys. Playwright handles navigation and isolated browser contexts.
// External providers are blocked; imports and real refresh checks run separately.
import assert from 'node:assert/strict';
import {existsSync,mkdirSync} from 'node:fs';
import {resolve,delimiter} from 'node:path';
import {pathToFileURL} from 'node:url';
let driver;
try{driver=await import('playwright');}catch{
 const entry=(process.env.PATH??'').split(delimiter).map(p=>resolve(p,'../playwright/index.mjs')).find(existsSync);
 if(!entry)throw Error('Run npm run test:browser to provide the pinned Playwright driver.');driver=await import(pathToFileURL(entry).href);
}
const origin=await localOrigin();
const libraries=resolve('.sites-runtime/browser-libs/root/usr/lib/x86_64-linux-gnu');
const browser=await driver.chromium.launch({headless:true,...(process.env.MNEMBA_TEST_BROWSER?{executablePath:process.env.MNEMBA_TEST_BROWSER}:{}),env:{...process.env,...(existsSync(libraries)?{LD_LIBRARY_PATH:libraries+(process.env.LD_LIBRARY_PATH?':'+process.env.LD_LIBRARY_PATH:'')}:{})}});
mkdirSync('outputs',{recursive:true});
const errors=[];
const {DatabaseSync}=await import('node:sqlite');const {readdirSync,writeFileSync}=await import('node:fs');
const root='.wrangler/state/v3/d1/miniflare-D1DatabaseObject/';const db=new DatabaseSync(populatedLocalDatabase(),{readOnly:true});
const historical=JSON.parse(db.prepare("SELECT payload FROM fixtures WHERE json_extract(payload,'$.home.name') LIKE '%Frankfurt%' AND json_extract(payload,'$.away.name') LIKE '%Bayern%' AND json_extract(payload,'$.round')='Matchday 1' ORDER BY starts_at LIMIT 1").get().payload);
const timed=JSON.parse(db.prepare("SELECT payload FROM fixtures WHERE json_extract(payload,'$.kickoffPrecision') IS NOT 'date' AND starts_at>0 ORDER BY starts_at DESC LIMIT 1").get().payload);db.close();
const report={historical:historical.id,timed:timed.id,zones:[],badges:[]};
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 async function visit(path){console.log('Visit '+path);await page.goto(origin+path,{waitUntil:'domcontentloaded',timeout:60000});await page.locator('h1').first().waitFor();}
 async function overflow(){assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal page overflow at '+page.url());}
 async function publicOnly(){for(const name of ['Basketball studio','Diagnostics','Prediction Lab','Data Sources','AI Studio'])assert.equal(await page.getByRole('link',{name,exact:false}).count(),0);assert.equal(await page.locator('a[href="/lab"]').count(),0);}
 for(const path of ['/','/lab','/football/admin','/football/classic?view=diagnostics']){await visit(path);await page.locator('.broadcast-action').waitFor();await publicOnly();if(path!=='/')assert.ok(page.url().endsWith('/football'));}
 for(const api of ['intelligence','football'])for(const view of ['sources','files','diagnostics','evidence','social','performance']){const r=await fetch(`${origin}/api/${api}?view=${view}`);assert.equal(r.status,403);}
 assert.equal((await fetch(origin+'/api/intelligence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job:'fixtures'})})).status,403);
 assert.equal((await fetch(origin+'/api/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"matchupId":"arsenal-city"}'})).status,410);
 await visit('/football');await page.waitForFunction(()=>document.querySelector('.broadcast-image')?.naturalWidth>0);await page.getByRole('heading',{name:'Matchday Picks'}).waitFor();assert.ok(!(await page.locator('body').innerText()).includes('Completed predictions: 0'));
 const first=await page.locator('.broadcast-copy h1').innerText();await page.getByRole('button',{name:'Next featured match',exact:true}).click();assert.notEqual(await page.locator('.broadcast-copy h1').innerText(),first);await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Motion reduced'}).waitFor();await page.locator('.insight-probabilities').first().waitFor();await page.screenshot({path:'outputs/page-upgrade/after-desktop.png'});
 for(const tab of ['Fixtures','Leagues','Teams & Players','News']){await page.locator('.intel-sidebar').getByRole('button',{name:tab,exact:true}).click();await publicOnly();await overflow();}
 await page.setViewportSize({width:390,height:844});await visit('/football?tab=Predictions');await page.waitForFunction(()=>document.querySelector('.broadcast-image')?.naturalWidth>0);await page.locator('.broadcast-action[href*="/match/"]').waitFor();await page.locator('.insight-probabilities').first().waitFor();await overflow();await page.screenshot({path:'outputs/page-upgrade/after-mobile.png'});
 await page.getByRole('button',{name:'Competition',exact:true}).click();await page.getByRole('textbox',{name:'Search competitions'}).fill('La Liga');await page.getByRole('dialog').getByRole('button',{name:/La Liga/}).waitFor();assert.equal(await page.getByRole('dialog').getByRole('button',{name:/La Liga/}).count(),1);await page.keyboard.press('Escape');
 for(const q of ['Messi','Cristiano Ronaldo','Mbappe','Mbape','Haaland','Salah','Kane','Bellingham','Vinicius','Saka']){await visit('/football/search?kind=player&q='+encodeURIComponent(q));await page.locator('a[role=option]').first().waitFor();assert.ok(await page.locator('a[href*="/football/player/"]').count()>0);await overflow();}
 await page.locator('a[href*="/football/player/"]').first().click();await page.getByRole('heading',{name:'Club association history'}).waitFor();await page.screenshot({path:'outputs/page-upgrade/player-mobile.png'});
 await visit('/football/match/'+encodeURIComponent(historical.id));await page.getByText('Form, head-to-head and standings',{exact:true}).click();await page.getByText('A meaningful pre-match ranking cannot be shown.',{exact:false}).waitFor();assert.equal(await page.locator('section').filter({has:page.getByRole('heading',{name:'Standings comparison',exact:true})}).locator('table tbody tr').count(),0);assert.equal(await page.getByRole('heading',{name:'Player membership and lineup evidence'}).count(),0);await overflow();await page.screenshot({path:'outputs/page-upgrade/historical-mobile.png'});
 const overview=await(await fetch(origin+'/api/intelligence?view=overview')).json();await visit('/football/news/'+(await import('../lib/football/consumer.mjs')).routeToken(overview.news[0].id));await page.getByRole('heading',{name:'What happened'}).waitFor();await page.locator('.article-figure .news-visual').waitFor();assert.equal(await page.locator('.article-figure img[src*="football-night"]').count(),0);await overflow();await page.screenshot({path:'outputs/page-upgrade/news-mobile.png'});
 const news=await(await fetch(origin+'/api/intelligence?view=news')).json();const videoStory=news.articles.find(n=>n.media?.permission==='publisher-embed');assert.ok(videoStory,'Real video briefing required');await visit('/football/news/'+(await import('../lib/football/consumer.mjs')).routeToken(videoStory.id));await page.getByRole('button',{name:'Play publisher video'}).click();await page.locator('iframe').waitFor();await page.waitForTimeout(3000);report.video={url:videoStory.id,frame:await page.locator('iframe').getAttribute('src'),body:await page.frameLocator('iframe').locator('body').innerText().catch(()=> 'Frame inaccessible')};await page.screenshot({path:'outputs/page-upgrade/video-mobile.png'});await overflow();
 const catalog=await(await fetch(origin+'/api/intelligence?view=badges')).json();for(const badge of Object.entries(catalog.badges).filter(([,b])=>b.url).slice(0,8)){const r=await fetch(badge[1].url);assert.ok(r.ok);report.badges.push({id:badge[0],status:r.status});}
 for(const name of ['Arsenal','FC Augsburg','AC Milan','FC Barcelona']){const team=(await(await fetch(origin+'/api/intelligence?view=global-search&kind=team&q='+encodeURIComponent(name))).json()).results[0];assert.ok(team);await visit(team.url);await page.waitForFunction(()=>[...document.querySelectorAll('.match-hero .team-badge img')].some(i=>i.naturalWidth>0));report.badges.push({name,loadedInBrowser:true});await page.screenshot({path:'outputs/page-upgrade/badge-'+name.replaceAll(' ','-')+'.png'});}
 const {formatKickoff}=await import('../lib/football/timezone.mjs');
 for(const zone of ['America/New_York','Africa/Dar_es_Salaam','Europe/London']){const c=await browser.newContext({timezoneId:zone,viewport:{width:1440,height:1000}});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/football/match/'+encodeURIComponent(timed.id));await p.getByText(formatKickoff(timed,zone),{exact:true}).first().waitFor();report.zones.push({zone,text:formatKickoff(timed,zone)});if(zone==='America/New_York'){await p.getByLabel('Timezone',{exact:true}).selectOption('Africa/Dar_es_Salaam');await p.getByText(formatKickoff(timed,'Africa/Dar_es_Salaam'),{exact:true}).first().waitFor();assert.ok(!p.url().includes('timezone'));await p.reload();await p.getByText(formatKickoff(timed,'Africa/Dar_es_Salaam'),{exact:true}).first().waitFor();await p.getByLabel('Timezone',{exact:true}).selectOption('local');}
 // Isolated response fixtures exercise midnight and DST rendering; never persisted.
 for(const instant of ['2026-03-29T00:30:00Z','2026-03-29T01:30:00Z','2026-11-01T06:30:00Z']){await p.route('**/api/intelligence?view=match-context*',async route=>{const response=await route.fetch();const body=await response.json();body.fixture={...body.fixture,startsAt:Date.parse(instant),kickoffPrecision:'instant'};await route.fulfill({json:body});});await p.reload();await p.getByText(formatKickoff({startsAt:Date.parse(instant)},zone),{exact:true}).first().waitFor();await p.unroute('**/api/intelligence?view=match-context*');}await c.close();}
 assert.deepEqual(errors,[]);writeFileSync('outputs/page-upgrade/browser-evidence.json',JSON.stringify(report,null,2));console.log('PASS: public navigation, redirects, internal access denial, imagery, slideshow, mobile layouts, real player search, historical season opener, news, badges and timezone/DST rendering.');
}finally{await browser.close();}
