import test from 'node:test';
import assert from 'node:assert/strict';
import {routeToken,providerId,deriveTable,matchContext} from '../../lib/football/consumer.mjs';
import {database,apiFixture} from '../football-db.mjs';
import {normalizeFixture} from '../../lib/football/providers.mjs';
import {IntelligenceService} from '../../lib/football/intelligence.mjs';
test('profile route tokens round trip provider escapes, Unicode and punctuation without nested encoding',()=>{for(const id of ['openfootball:FC%20Augsburg','openfootball:Eintracht%20Frankfurt','Würzburg / 你好']){assert.equal(providerId(routeToken(id)),id);assert.ok(!routeToken(id).includes('%'));}assert.equal(providerId('legacy:1'),'legacy:1');});
test('derived standings exclude future results and respect home/away splits',()=>{const make=(id,time,h,a)=>({id,home:{id:'h',name:'Home'},away:{id:'a',name:'Away'},homeScore:h,awayScore:a,status:'FT',startsAt:time});const fixtures=[make('1',1,2,0),make('2',3,0,9)];const rows=deriveTable(fixtures,2);assert.equal(rows[0].team.id,'h');assert.equal(rows[0].points,3);assert.equal(rows[0].goalsAgainst,0);assert.equal(deriveTable(fixtures,2,'away').find(r=>r.team.id==='h').played,0);});

import {parseFootballText} from '../../lib/football/adapters.mjs';
test('German score-between format separates kickoff and half-time from participants',()=>{const r=parseFootballText('= Bundesliga\nSat Dec 13 2025\n15:30   Eintracht Frankfurt  1-0 (0-0)  FC Augsburg',{year:2025});assert.equal(r.fixtures[0].team1,'Eintracht Frankfurt');assert.equal(r.fixtures[0].team2,'FC Augsburg');assert.deepEqual(r.fixtures[0].score.ft,[1,0]);});
test('consumer match context and search use persisted records and exclude analyzed outcome',async()=>{const {store,sqlite}=database();try{await store.init();const service=new IntelligenceService(store);await service.initialize();const fixtures=[normalizeFixture('api-football',apiFixture(900,'FT','2025-01-01T12:00:00Z')),normalizeFixture('api-football',apiFixture(901,'FT','2025-02-01T12:00:00Z'))];await service.saveFixtures(fixtures);const context=await matchContext(service,fixtures[1].id);assert.equal(context.h2h.games,1);assert.equal(context.form[0].overall.games,1);assert.equal(context.table.rows[0].played,1);assert.equal(context.analysis.probabilities,undefined);const search=await service.read(new URLSearchParams({view:'global-search',q:'Team 10'}));assert.ok(search.results.some(r=>r.kind==='team'));const token=search.results.find(r=>r.kind==='team').url.split('/').at(-1);const entity=await service.read(new URLSearchParams({view:'entity',id:token}));assert.equal(entity.entity.name,'Team 10');}finally{sqlite.close();}});
test('history follows corroborated aliases without merging unverified similar participants',async()=>{const {store,sqlite}=database();try{await store.init();const service=new IntelligenceService(store);await service.initialize();const fixtures=[normalizeFixture('api-football',apiFixture(910,'FT','2025-01-01T12:00:00Z',10,20)),normalizeFixture('api-football',apiFixture(911,'FT','2025-02-01T12:00:00Z',11,20))];await service.saveFixtures(fixtures);assert.equal((await service.history(fixtures[0].home.id)).length,1);const alias=await store.one('SELECT canonical_id FROM entity_aliases WHERE provider_id=?',fixtures[0].home.id);await service.evidence.reconcileAlias(fixtures[1].home.id,alias.canonical_id,'https://www.wikidata.org/wiki/Q15755');const history=await service.history(fixtures[0].home.id);assert.equal(history.length,2);assert.ok(history.every(f=>f.home.id===fixtures[0].home.id));}finally{sqlite.close();}});
