import test from 'node:test';
import assert from 'node:assert/strict';
import {database,apiFixture} from '../football-db.mjs';
import {IntelligenceService} from '../../lib/football/intelligence.mjs';
import {normalizeFixture} from '../../lib/football/providers.mjs';
import {matchState,analysisCutoff} from '../../lib/football/match-state.mjs';
import {sameOrigin} from '../../lib/football/access.mjs';
test('status, never a passed clock, determines completion',()=>{const now=Date.parse('2026-09-12T15:00:00Z'),f={startsAt:Date.parse('2026-09-12T12:00:00Z'),status:'NS',kickoffPrecision:'date'};assert.equal(matchState(f,now).state,'scheduled');assert.equal(matchState(f,now).previewAllowed,true);assert.equal(matchState(f,now).forecastEligible,false);assert.equal(matchState(f,now).needsRefresh,false);assert.equal(analysisCutoff(f,now),Date.parse('2026-09-12'));for(const [status,state] of [['1H','live'],['FT','completed'],['PST','postponed'],['CANC','cancelled'],['SUSP','interrupted']])assert.equal(matchState({...f,status},now).state,state);assert.equal(matchState({...f,kickoffPrecision:'instant'},now).needsRefresh,true);});
test('date-only scheduled match remains analyzable after its placeholder on matchday',async()=>{const {store,sqlite}=database();store.now=()=>Date.parse('2026-09-12T15:00:00Z');try{await store.init();const service=new IntelligenceService(store);await service.initialize();const history=[1,2,3,4].map(i=>normalizeFixture('api-football',apiFixture(700+i,'FT',`2026-09-0${i}T12:00:00Z`)));const f={...normalizeFixture('api-football',apiFixture(710,'NS','2026-09-12T12:00:00Z')),kickoffPrecision:'date'};await service.saveFixtures([...history,f]);for(const view of ['analysis','match-context']){const r=await service.read(new URLSearchParams({view,id:f.id}));assert.equal(r.fixture.lifecycle.state,'scheduled');assert.ok(r.analysis.probabilities);assert.equal(r.analysis.estimateKind,'exploratory');assert.ok(!r.analysis.label.includes('Historical'));}}finally{sqlite.close();}});
test('forwarded HTTPS refresh accepts only the same host and rejects cross-site requests',()=>{const headers={Origin:'https://preview.example','X-Forwarded-Proto':'https'};assert.equal(sameOrigin(new Request('http://preview.example/api',{headers})),true);assert.equal(sameOrigin(new Request('http://preview.example/api',{headers:{...headers,Origin:'https://evil.example'}})),false);assert.equal(sameOrigin(new Request('http://preview.example/api',{headers:{...headers,'Sec-Fetch-Site':'cross-site'}})),false);});
import {ModelLab} from '../../lib/football/model-lab.mjs';
import {archiveFor,compareForecast} from '../../lib/football/forecast-history.mjs';
import {normalizeLineups} from '../../lib/football/probable-lineup.mjs';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
test('immutable forecast survives live, finish, corrections, void and database restart',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'mnemba-lifecycle-')),path=join(dir,'test.sqlite');let db=database(path),now=Date.parse('2026-09-10T12:00:00Z');db.store.now=()=>now;
 try{await db.store.init();let service=new IntelligenceService(db.store);await service.initialize();await service.saveFixtures([1,2,3,4].map(i=>normalizeFixture('api-football',apiFixture(800+i,'FT',`2026-09-0${i}T12:00:00Z`))));const f=normalizeFixture('api-football',apiFixture(810,'NS','2026-09-11T12:00:00Z'));await service.saveFixtures([f]);const lab=new ModelLab(service);await lab.capture(f);const original=(await archiveFor(service,f)).original;assert.ok(original);now=f.startsAt+60000;await service.saveFixtures([{...f,status:'1H'}]);assert.equal((await service.read(new URLSearchParams({view:'analysis',id:f.id}))).analysis.archive.original.id,original.id);
 await service.saveFixtures([{...f,status:'FT',homeScore:2,awayScore:1}]);assert.equal((await lab.performance()).versions[0].count,1);assert.equal(await lab.grade(),0);await service.saveFixtures([{...f,status:'FT',homeScore:0,awayScore:0}]);assert.equal((await archiveFor(service,f)).selected.grade.homeScore,0);const audits=await db.store.all('SELECT * FROM analysis_grade_audit WHERE forecast_id=?',original.id);assert.ok(audits.length>=3);await assert.rejects(db.store.run("UPDATE analysis_forecasts SET payload='{}'"),/immutable/);
 db.sqlite.close();db=database(path);db.store.now=()=>now;await db.store.init();service=new IntelligenceService(db.store);assert.equal((await archiveFor(service,f)).original.id,original.id);await service.saveFixtures([{...f,status:'PST',startsAt:f.startsAt+86400000}]);assert.equal((await new ModelLab(service).performance()).versions[0].count,0);assert.equal((await archiveFor(service,f)).selected.gradeState,'void');
 }finally{db.sqlite.close();rmSync(dir,{recursive:true,force:true});}
});
test('analysis pagination processes beyond 150 and records failures without stopping',async()=>{const {store,sqlite}=database();store.now=()=>Date.parse('2026-09-10');try{await store.init();const service=new IntelligenceService(store);await service.initialize();await service.saveFixtures(Array.from({length:161},(_,i)=>normalizeFixture('api-football',apiFixture(1000+i,'NS','2026-09-11T12:00:00Z',10+i,500+i))));const lab=new ModelLab(service);let attempts=0;lab.capture=async()=>{attempts++;if(attempts===2)throw Error('isolated provider failure');return{state:'abstained',reason:'partial coverage'};};let result;do{result=await lab.update({pageSize:40});}while(!result.complete);assert.equal(attempts,161);assert.equal((await store.one('SELECT COUNT(*) n FROM analysis_processing')).n,161);assert.equal((await store.one("SELECT COUNT(*) n FROM analysis_processing WHERE state='error'")).n,1);assert.equal((await lab.evaluateCandidate()).state,'collecting');}finally{sqlite.close();}});
test('normalizes provider team sheets and compares ties without arbitrary winners',()=>{const raw=[{team:{id:10},startXI:[{player:{id:1,name:'Keeper',pos:'G'}}]}];assert.deepEqual(normalizeLineups(raw,'api-football')[0].players[0],{id:'api-football:1',name:'Keeper',position:'GK',started:true});const result=compareForecast({probabilities:[.4,.4,.2],distribution:[{home:1,away:0,probability:.2},{home:0,away:0,probability:.2}]},0,0);assert.equal(result.resultCorrect,null);assert.equal(result.exactScoreCorrect,null);});
test('historical cutoff precedes limit, and insufficient history keeps useful factors',async()=>{const {store,sqlite}=database();store.now=()=>Date.parse('2026-09-12');try{await store.init();const service=new IntelligenceService(store);await service.initialize();const old=normalizeFixture('api-football',apiFixture(2000,'FT','2020-01-01T12:00:00Z'));await service.saveFixtures([old]);const insert=sqlite.prepare("INSERT INTO fixtures SELECT ? ,provider,?1,competition_id,season_id,home_team_id,away_team_id,?,status,home_score,away_score,label,json_set(payload,'$.id',?,'$.startsAt',?),updated_at FROM fixtures WHERE id=?");for(let i=0;i<2001;i++)insert.run('later:'+i,Date.parse('2025-01-01'),'later:'+i,Date.parse('2025-01-01'),old.id);const history=await service.history(old.home.id,old.away.id,Date.parse('2021-01-01'));assert.equal(history.length,1);const f={...old,id:'api-football:2001',externalId:'2001',status:'NS',startsAt:Date.parse('2021-01-02'),kickoffPrecision:'date'};await service.saveFixtures([f]);const r=await service.read(new URLSearchParams({view:'analysis',id:f.id}));assert.ok(r.analysis.factors);assert.ok(!r.analysis.probabilities);}finally{sqlite.close();}});
test('candidate uses locked chronological prospective pairs and can roll back',async()=>{const {store,sqlite}=database();store.now=()=>Date.parse('2026-09-12');try{await store.init();const service=new IntelligenceService(store);await service.initialize();const f=normalizeFixture('api-football',apiFixture(3000,'FT','2026-01-01'));await service.saveFixtures([f]);for(let i=0;i<200;i++){const id=`trial:${i}`,kickoff=f.startsAt+i*86400000;await store.run("INSERT INTO fixtures SELECT ?,provider,?1,competition_id,season_id,home_team_id,away_team_id,?,status,home_score,away_score,label,json_set(payload,'$.id',?,'$.startsAt',?),updated_at FROM fixtures WHERE id=?",id,kickoff,id,kickoff,f.id);for(const version of ['poisson-temporal-1','dc-candidate-1']){const forecast=id+version,payload={probabilities:version==='poisson-temporal-1'?[.4,.3,.3]:[.8,.1,.1],parameterCutoff:kickoff-2000,competitionId:f.competition.id};await store.run('INSERT INTO analysis_forecasts VALUES(?,?,?,?,?,?,?,?,?)',forecast,id,version,kickoff-1000,kickoff,kickoff-1000,1,JSON.stringify(payload),'[]');await store.upsert('analysis_grades',{id:forecast,fixture_id:id,result_known_at:kickoff+7200000,outcome:0,payload:'{}'});}}const lab=new ModelLab(service),result=await lab.evaluateCandidate();assert.equal(result.state,'promoted');assert.equal(result.validation.candidate.count,100);assert.equal(result.heldOut.candidate.count,100);assert.deepEqual(await lab.evaluateCandidate(),result);assert.equal((await lab.rollback()).primary,'poisson-temporal-1');}finally{sqlite.close();}});

test('proxy-rewritten request URL uses matching forwarded host, never a different origin',()=>{const headers={Origin:'https://preview.example','X-Forwarded-Host':'preview.example','X-Forwarded-Proto':'https'};assert.equal(sameOrigin(new Request('http://localhost:5173/api',{headers})),true);assert.equal(sameOrigin(new Request('http://localhost:5173/api',{headers:{...headers,Origin:'https://evil.example'}})),false);});

test('local worker may rewrite proxy transport protocol without changing public host',()=>{assert.equal(sameOrigin(new Request('http://localhost/api',{headers:{Origin:'https://preview.example','X-Forwarded-Host':'preview.example','X-Forwarded-Proto':'http'}})),true);});
